#!/usr/bin/env python

import ROOT as root
from helpers import *
root.gROOT.SetBatch(True)

if __name__ == "__main__":

  cuts = ""
  #cuts += "*(isMC || ((triggerBits >> 4) & 1))" # BEAMON trigger
  #cuts += "*(isMC || ((triggerBits >> 10) & 1))" # COSMICON trigger
  #cuts += "*(isMC || !((triggerBits >> 10) & 1))" # Not COSMICON trigger
  #cuts += "*(isMC || ((triggerBits >> 11) & 1))" # COSMIC trigger
  #cuts += "*(isMC || (nWCTracks ==0 && nTOFs ==0))"
  cuts += "*( iBestMatch >= 0)" # primary Track found
  #cuts += "*(acos(sin(primTrkStartTheta)*sin(primTrkStartPhi))*180./pi < 5. || acos(sin(primTrkStartTheta)*sin(primTrkStartPhi))*180./pi > 175.)" # theta vertical
  #cuts += "*((!isMC) || (trueStartMom>3000. && trueStartMom < 8000.))"

  #cuts += "*enterExitYm*enterExitYp"
  #cuts += "*(primTrkXs > 10. && primTrkXs < 38. &&  primTrkYs > 15. && primTrkZs > 10. && primTrkZs > 80.)"
  #cuts += "*(primTrkYs > 15.)"

  weightStr = "1"+cuts
  nData = 30860.0
  logy = True

  c = root.TCanvas()
  NMAX=1000000000
  #NMAX=1000
  fileConfigs = [
    #{
    #  #'fn': "/lariat/app/users/jhugon/lariatsoft_v06_15_00/srcs/lariatsoft/JobConfigurations/CosmicAna_Pos_RunII.root",
    #  'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_data_cosmics_Pos_RunII_v01/anahist.root",
    #  'name': "RunIIPos",
    #  'title': "Run II Positive Polarity",
    #  'caption': "Run II Positive Polarity",
    #  'color': root.kBlack,
    #  'isData': True,
    #},
    #{
    #  'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_data_cosmics_Neg_RunII_v01/anahist.root",
    #  'name': "RunIINeg",
    #  'title': "Run II Negative Polarity",
    #  'caption': "Run II Negative Polarity",
    #  'color': root.kGreen+3,
    #  'isData': True,
    #},
    {
      'fn': ["/scratch/jhugon/cosmicDataTrees/CosmicAna_RIIP60_64a.root",
             "/scratch/jhugon/cosmicDataTrees/CosmicAna_RIIP60_64b.root",
             "/scratch/jhugon/cosmicDataTrees/CosmicAna_RIIP60_64c.root"],
      'name': "RunIIP60",
      'title': "Run II+ 60 A",
      'caption': "Run II+ 60 A",
      'color': root.kBlack,
      'isData': True,
    },
    {
      #'fn': "/home/jhugon/cvmfs_lariat_v06_34_01/srcs/lariatsoft/JobConfigurations/textTestCosmicAna.root",
      'fn': "/scratch/jhugon/lariat/MC/Cosmics_v01/cosmicAna2.root",
      'name': "CosmicMC",
      'title': "Cosmic MC",
      'caption': "Cosmic MC",
      'isData': False,
      #'scaleFactor': nData/17000.
    },
#    {
#      'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_PiAbsAndChEx_cosmics_vert_presmear20perc_v3/anahist.root",
#      'name': "CosmicMC_presmear20perc",
#      'title': "Cosmic MC Pre-smear 20% ",
#      'caption': "Cosmic MC Pre-smear 20%",
#      'isData': False,
#      'scaleFactor': 1367./99692.
#    },
#    {
#      'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_PiAbsAndChEx_cosmics_vert_presmear30perc_v3/anahist.root",
#      'name': "CosmicMC_presmear30perc",
#      'title': "Cosmic MC Pre-smear 30% ",
#      'caption': "Cosmic MC Pre-smear 30%",
#      'isData': False,
#      'scaleFactor': 1367./19365.
#    },
#    {
#      'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_PiAbsAndChEx_cosmics_vert_presmear35perc_v3/anahist.root",
#      'name': "CosmicMC_presmear35perc",
#      'title': "Cosmic MC Pre-smear 35% ",
#      'caption': "Cosmic MC Pre-smear 35%",
#      'isData': False,
#      'scaleFactor': 1367./19379.
#    },
#    {
#      'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_PiAbsAndChEx_cosmics_vert_presmear40perc_v3/anahist.root",
#      'name': "CosmicMC_presmear40perc",
#      'title': "Cosmic MC Pre-smear 40% ",
#      'caption': "Cosmic MC Pre-smear 40%",
#      'isData': False,
#      'scaleFactor': 1367./110166.
#    },
#    {
#      'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_PiAbsAndChEx_cosmics_vert_postsmear10perc_v3/anahist.root",
#      'name': "CosmicMC_postsmear10perc",
#      'title': "Cosmic MC Post-smear 10% ",
#      'caption': "Cosmic MC Post-smear 10%",
#      'isData': False,
#      'scaleFactor': 1367./109553.
#    },
#    {
#      'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_PiAbsAndChEx_cosmics_vert_postsmear20perc_v3/anahist.root",
#      'name': "CosmicMC_postsmear20perc",
#      'title': "Cosmic MC Post-smear 20% ",
#      'caption': "Cosmic MC Post-smear 20%",
#      'isData': False,
#      'scaleFactor': 1367./112612.
#    },
#   {
#     'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_PiAbsAndChEx_cosmics_vert_postsmear40perc_v3/anahist.root",
#     'name': "CosmicMC_postsmear40perc",
#     'title': "Cosmic MC Post-smear 40% ",
#     'caption': "Cosmic MC Post-smear 40%",
#     'isData': False,
#     'scaleFactor': 1367./110166.
#   },
#   {
#     'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_PiAbsAndChEx_cosmics_vert_postsmear60perc_v3/anahist.root",
#     'name': "CosmicMC_postsmear60perc",
#     'title': "Cosmic MC Post-smear 60% ",
#     'caption': "Cosmic MC Post-smear 60%",
#     'isData': False,
#     'scaleFactor': 1367./25596.
#   },
#   {
#     'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_PiAbsAndChEx_cosmics_vert_postsmear80perc_v3/anahist.root",
#     'name': "CosmicMC_postsmear80perc",
#     'title': "Cosmic MC Post-smear 80% ",
#     'caption': "Cosmic MC Post-smear 80%",
#     'isData': False,
#     'scaleFactor': 1367./25042.
#   },
    #{
    #  'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_PiAbsAndChEx_cosmics_vert_postsmear120perc_v3/anahist.root",
    #  'name': "CosmicMC_postsmear120perc",
    #  'title': "Cosmic MC Post-smear 120% ",
    #  'caption': "Cosmic MC Post-smear 120%",
    #  'isData': False,
    #  'scaleFactor': 1367./21010.
    #},
    #{
    #  'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_PiAbsAndChEx_cosmics_vert_postnoise10perc_v3/anahist.root",
    #  'name': "CosmicMC_2xNoise",
    #  'title': "Cosmic MC 2x Noise",
    #  'caption': "Cosmic MC 2x Noise",
    #  'isData': False,
    #  'scaleFactor': 1367./110413.
    #},
  ]

  for i in range(len(fileConfigs)):
    if not ('isData' in fileConfigs[i]) or not fileConfigs[i]['isData']:
        fileConfigs[i]['color'] = COLORLIST[i-1]

  histConfigs = [
#    {
#      'name': "trackXFront",
#      'xtitle': "X of TPC Track Projection to TPC Front [cm]",
#      'ytitle': "TPC Tracks / bin",
#      'binning': [50,0,50],
#      'var': "trackXFront",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackYFront",
#      'xtitle': "Y of TPC Track Projection to TPC Front [cm]",
#      'ytitle': "TPC Tracks / bin",
#      'binning': [50,-50,50],
#      'var': "trackYFront",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackMatchLowestZ",
#      'xtitle': "TPC Track Start Z [cm]",
#      'ytitle': "TPC Tracks / bin",
#      'binning': [40,0,20],
#      'var': "trackMatchLowestZ",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "nTOFs",
#      'xtitle': "Number of TOF Objects",
#      'ytitle': "Events / bin",
#      'binning': [11,0,10],
#      'var': "nTOFs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackStartX",
#      'xtitle': "TPC Track Start X [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-20,60],
#      'var': "trackStartX",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackStartY",
#      'xtitle': "TPC Track Start Y [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-50,50],
#      'var': "trackStartY",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackStartZ",
#      'xtitle': "TPC Track Start Z [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-20,110],
#      'var': "trackStartZ",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackEndX",
#      'xtitle': "TPC Track End X [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-20,60],
#      'var': "trackEndX",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackEndY",
#      'xtitle': "TPC Track End Y [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-50,50],
#      'var': "trackEndY",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackEndZ",
#      'xtitle': "TPC Track End Z [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-20,110],
#      'var': "trackEndZ",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackLength",
#      'xtitle': "TPC Track Length [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-10,100],
#      'var': "trackLength",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
    #{
    #  'name': "trackCaloKin",
    #  'xtitle': "TPC Calo Estimate of KE [MeV]",
    #  'ytitle': "Tracks / bin",
    #  'binning': [50,0,2500],
    #  'var': "trackCaloKin",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "primTrkLength",
      'xtitle': "Primary TPC Track Length [cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,100],
      'var': "primTrkLength",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
      'printIntegral': True,
    },
    {
      'name': "primTrkStartTheta",
      'xtitle': "Primary TPC Track #theta [deg]",
      'ytitle': "Events / bin",
      'binning': [180,0,180],
      'var': "primTrkStartTheta*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartCosTheta",
      'xtitle': "Primary TPC Track cos(#theta)",
      'ytitle': "Events / bin",
      'binning': [100,0,1],
      'var': "cos(primTrkStartTheta)",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartPhi",
      'xtitle': "Primary TPC Track #phi [deg]",
      'ytitle': "Events / bin",
      'binning': [180,-180,180],
      'var': "primTrkStartPhi*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartThetaY",
      'xtitle': "Primary TPC Track #theta_{y} [deg]",
      'ytitle': "Events / bin",
      'binning': [180,0,180],
      'var': "acos(sin(primTrkStartTheta)*sin(primTrkStartPhi))*180./pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartCosThetaY",
      'xtitle': "Primary TPC Track cos(#theta_{y})",
      'ytitle': "Events / bin",
      'binning': [100,0,1],
      'var': "sin(primTrkStartTheta)*sin(primTrkStartPhi)",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartPhiZX",
      'xtitle': "Primary TPC Track #phi_{zx} [deg]",
      'ytitle': "Events / bin",
      'binning': [180,-180,180],
      'var': "atan2(sin(primTrkStartTheta)*cos(primTrkStartPhi),cos(primTrkStartTheta))*180./pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartThetaX",
      'xtitle': "Primary TPC Track #theta_{x} [deg]",
      'ytitle': "Events / bin",
      'binning': [180,0,180],
      'var': "acos(sin(primTrkStartTheta)*cos(primTrkStartPhi))*180./pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartCosThetaX",
      'xtitle': "Primary TPC Track cos(#theta_{x})",
      'ytitle': "Events / bin",
      'binning': [100,0,1],
      'var': "sin(primTrkStartTheta)*cos(primTrkStartPhi)",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartPhiZY",
      'xtitle': "Primary TPC Track #phi_{zy} [deg]",
      'ytitle': "Events / bin",
      'binning': [180,-180,180],
      'var': "atan2(sin(primTrkStartTheta)*sin(primTrkStartPhi),cos(primTrkStartTheta))*180./pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs_zoom",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,10],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      'normalize': not logy,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs_zoom2",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,10],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      'normalize': logy,
      'logy': not logy,
    },
    {
      'name': "primTrkdEdxs_zoom3",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [50,0,5],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      'normalize': logy,
      'logy': not logy,
    },
#    {
#      'name': "primTrkTruedEdxs",
#      'xtitle': "Primary TPC Track True dE/dx [MeV/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,50],
#      'var': "primTrkTruedEdxs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "primTrkTruedEdxs_zoom",
#      'xtitle': "Primary TPC Track True dE/dx [MeV/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,10],
#      'var': "primTrkTruedEdxs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "primTrkdQdxs",
#      'xtitle': "Primary TPC Track dQ/dx [ADC/cm]",
#      'ytitle': "Events / bin",
#      'binning': [300,0,3e4],
#      'var': "primTrkdQdxs*((0.5-1.)*isMC + 1.)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "primTrkdQdxs_zoom",
#      'xtitle': "Primary TPC Track dQ/dx [ADC/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,8e3],
#      'var': "primTrkdQdxs*((0.5-1.)*isMC + 1.)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#      'printIntegral' : True,
#    },
#    {
#      'name': "primTrkdQdxs_zoom2",
#      'xtitle': "Primary TPC Track dQ/dx [ADC/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,8e3],
#      'var': "primTrkdQdxs*((0.5-1.)*isMC + 1.)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': not logy,
#      'printIntegral' : True,
#    },
#    {
#      'name': "primTrkdQs",
#      'xtitle': "Primary TPC Track dQ [ADC]",
#      'ytitle': "Events / bin",
#      'binning': [200,0,8e3],
#      'var': "primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': not logy,
#      'printIntegral' : True,
#    },
#    {
#      'name': "primTrkTruedQdxs",
#      'xtitle': "Primary TPC Track True dQ/dx [e^{-}/cm]",
#      'ytitle': "Events / bin",
#      'binning': [200,0,5e6],
#      'var': "primTrkTruedQdxs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "primTrkTruedQdxs_zoom",
#      'xtitle': "Primary TPC Track True dQ/dx [e^{-}/cm]",
#      'ytitle': "Events / bin",
#      'binning': [200,0,1e5],
#      'var': "primTrkTruedQdxs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "primTrkTruedQs",
#      'xtitle': "Primary TPC Track Q [e^{-}]",
#      'ytitle': "Events / bin",
#      #'binning': [200,0,1e5],
#      'binning': getLogBins(100,1e3,1e7),
#      'var': "primTrkTruedQs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#      'logx': True,
#    },
#    {
#      'name': "primTrkTruedQs2",
#      'xtitle': "Primary TPC Track Q [e^{-}]",
#      'ytitle': "Events / bin",
#      'binning': [200,0,2e5],
#      'var': "primTrkTruedQs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': not logy,
#      'logx': False,
#    },
#    {
#      'name': "primTrkdEdxs_Q1000to1500_zoom2",
#      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,10],
#      'var': "primTrkdEdxs",
#      'cuts': weightStr+"*(primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) > 1000. && primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) < 1500.)",
#      #'normalize': True,
#      'logy': not logy,
#      'caption': "1000 ADC < Q < 1500 ADC",
#    },
#    {
#      'name': "primTrkdEdxs_Q1500to2000_zoom2",
#      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,10],
#      'var': "primTrkdEdxs",
#      'cuts': weightStr+"*(primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) > 1500. && primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) < 2000.)",
#      #'normalize': True,
#      'logy': not logy,
#      'caption': "1500 ADC < Q < 2000 ADC",
#    },
#    {
#      'name': "primTrkdEdxs_Q2000to3000_zoom2",
#      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,10],
#      'var': "primTrkdEdxs",
#      'cuts': weightStr+"*(primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) > 2000. && primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) < 3000.)",
#      #'normalize': True,
#      'logy': not logy,
#      'caption': "2000 ADC < Q < 3000 ADC",
#    },
#    {
#      'name': "primTrkdEdxs_Q3000to4000_zoom2",
#      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,10],
#      'var': "primTrkdEdxs",
#      'cuts': weightStr+"*(primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) > 3000. && primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) < 4000.)",
#      #'normalize': True,
#      'logy': not logy,
#      'caption': "3000 ADC < Q < 4000 ADC",
#    },
    #{
    #  'name': "primTrkdEdxsFidCut",
    #  'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
    #  'ytitle': "Events / bin",
    #  'binning': [200,0,50],
    #  'var': "primTrkdEdxs",
    #  'cuts': weightStr+"*primTrkInFids",
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "primTrkResRanges",
      'xtitle': "Primary TPC Track Residual Range [cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,100],
      'var': "primTrkResRanges",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkPitches",
      'xtitle': "Primary TPC Track Pitch [cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,10],
      'var': "primTrkPitches",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    #{
    #  'name': "primTrkEndKin",
    #  'xtitle': "Primary TPC Track End Kinetic Energy [MeV]",
    #  'ytitle': "Events / bin",
    #  'binning': [50,0,1000],
    #  'var': "primTrkEndKin",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "primTrkEndKinFid",
    #  'xtitle': "Primary TPC Track End Kinetic Energy [MeV]",
    #  'ytitle': "Events / bin",
    #  'binning': [50,0,1000],
    #  'var': "primTrkEndKinFid",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trueEndProcess",
    #  'xtitle': "trueEndProcess",
    #  'ytitle': "Events / bin",
    #  'binning': [17,0,17],
    #  'var': "trueEndProcess",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trueStartTheta",
    #  'xtitle': "True Start #theta [deg]",
    #  'binning': [90,0,180],
    #  'var': "trueStartTheta*180/pi",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #},
    #{
    #  'name': "trueStartPhi",
    #  'xtitle': "True Start #phi",
    #  'binning': [90,-180,180],
    #  'var': "trueStartPhi*180/pi",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #},
    #{
    #  'name': "trueStartThetaY",
    #  'xtitle': "True Start #theta_{y} [deg]",
    #  'ytitle': "Events / bin",
    #  'binning': [180,0,180],
    #  'var': "acos(sin(trueStartTheta)*sin(trueStartPhi))*180./pi",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trueStartPhiZX",
    #  'xtitle': "True Start #theta_{zx} [deg]",
    #  'ytitle': "Events / bin",
    #  'binning': [180,-180,180],
    #  'var': "atan2(sin(trueStartTheta)*cos(trueStartPhi),cos(trueStartTheta))*180./pi",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trueStartThetaX",
    #  'xtitle': "True Start #theta_{x} [deg]",
    #  'ytitle': "Events / bin",
    #  'binning': [180,0,180],
    #  'var': "acos(sin(trueStartTheta)*cos(trueStartPhi))*180./pi",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trueStartPhiZY",
    #  'xtitle': "True Start #theta_{zy} [deg]",
    #  'ytitle': "Events / bin",
    #  'binning': [180,-180,180],
    #  'var': "atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180./pi",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "trueStartE",
      'xtitle': "Muon True Initial Momentum [GeV]",
      'ytitle': "Events / bin",
      'binning': [100,0,300],
      'var': "1e-3*trueStartE",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
      #'printIntegral': True,
    },
    {
      'name': "trueStartE_zoom",
      'xtitle': "Muon True Initial Momentum [GeV]",
      'ytitle': "Events / bin",
      'binning': [40,0,10],
      'var': "1e-3*trueStartE",
      'cuts': weightStr,
      #'normalize': True,
      'logy': False,
      #'printIntegral': True,
    },
  ]

  plotManyFilesOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_")
#  fileConfigMCs = copy.deepcopy(fileConfigs)
#  fileConfigData = None
#  for i in reversed(range(len(fileConfigMCs))):
#    if 'isData' in fileConfigMCs[i] and fileConfigMCs[i]['isData']:
#      fileConfigData = fileConfigMCs.pop(i)
#  DataMCStack(fileConfigData,fileConfigMCs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX)

########################################################
########################################################
########################################################

  histConfigs = [
    {
      'name': "primTrkdEdxs",
      'title': "All",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      'color': root.kBlack,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs",
      'title': "x < 10 cm",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr + "*(primTrkXs < 10.)",
      'color': root.kBlue-7,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs",
      'title': "10 cm < x < 20 cm",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr + "*(primTrkXs > 10. && primTrkXs < 20.)",
      'color': root.kRed-4,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs",
      'title': "20 cm < x < 30 cm",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr + "*(primTrkXs > 20. && primTrkXs < 30.)",
      'color': root.kGreen,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs",
      'title': "30 cm < x < 40 cm",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr + "*(primTrkXs > 30. && primTrkXs < 40.)",
      'color': root.kMagenta-4,
      #'normalize': True,
      'logy': logy,
    },
  ]

#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_dEdxForX")

########################################################
########################################################
########################################################

  histConfigs = [
    {
      'name': "primTrkdEdxVRange",
      'xtitle': "Primary Track Hit Residual Range [cm]",
      'ytitle': "Primary Track Hit dE/dx [MeV/cm]",
      'binning': [100,0,100,100,0,50],
      'var': "primTrkdEdxs:primTrkResRanges",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
#    {
#      'name': "primTrkdEdxVRangeFidCut",
#      'xtitle': "Primary Track Hit Residual Range [cm]",
#      'ytitle': "Primary Track Hit dE/dx [MeV/cm]",
#      'binning': [100,0,100,100,0,50],
#      'var': "primTrkdEdxs:primTrkResRanges",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "trackYFrontVtrackXFront",
#      'xtitle': "X of TPC Track Projection to TPC Front [cm]",
#      'ytitle': "Y of TPC Track Projection to TPC Front [cm]",
#      'binning': [40,0,40,40,-20,20],
#      'var': "trackYFront:trackXFront",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
    {
      'name': "primTrkdEdxVwire",
      'xtitle': "Primary Track Hit Wire Number",
      'ytitle': "Primary Track Hit dE/dx [MeV/cm]",
      'binning': [240,0,240,100,0,10],
      'var': "primTrkdEdxs:primTrkTrueWires",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
    {
      'name': "primTrkStartThetaVPhi",
      'xtitle': "Primary TPC Track #phi [deg]",
      'ytitle': "Primary TPC Track #theta [deg]",
      'binning': [90,-180,180,90,0,180],
      'var': "primTrkStartTheta*180/pi:primTrkStartPhi*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
    {
      'name': "primTrkStartThetaYVprimTrkStartPhiZX",
      'xtitle': "Primary TPC Track #phi_{zx} [deg]",
      'ytitle': "Primary TPC Track #theta_{y} [deg]",
      'binning': [90,-180,180,90,0,180],
      'var': "acos(sin(primTrkStartTheta)*sin(primTrkStartPhi))*180/pi:atan2(sin(primTrkStartTheta)*cos(primTrkStartPhi),cos(primTrkStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkStartThetaYVprimTrkStartPhiZX_Zoom",
      'xtitle': "Primary TPC Track #phi_{zx} [deg]",
      'ytitle': "Primary TPC Track #theta_{y} [deg]",
      'binning': [45,0,45,80,50,130],
      'var': "acos(sin(primTrkStartTheta)*sin(primTrkStartPhi))*180/pi:atan2(sin(primTrkStartTheta)*cos(primTrkStartPhi),cos(primTrkStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkStartThetaXVprimTrkStartPhiZY",
      'xtitle': "Primary TPC Track #phi_{zy} [deg]",
      'ytitle': "Primary TPC Track #theta_{x} [deg]",
      'binning': [90,-180,180,90,0,180],
      'var': "acos(sin(primTrkStartTheta)*cos(primTrkStartPhi))*180/pi:atan2(sin(primTrkStartTheta)*sin(primTrkStartPhi),cos(primTrkStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
#    {
#      'name': "primTrkdEdxsVx",
#      'xtitle': "Hit x [cm]",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [20,0,50,10000,0,50],
#      'var': "primTrkdEdxs:primTrkXs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
#    {
#      'name': "primTrkdEdxsVy",
#      'xtitle': "Hit y [cm]",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [20,-25,25,10000,0,50],
#      'var': "primTrkdEdxs:primTrkYs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
#    {
#      'name': "primTrkdEdxsVz",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [50,-5,95,10000,0,50],
#      'var': "primTrkdEdxs:primTrkZs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
#    {
#      'name': "primTrkdEdxsVrun",
#      'xtitle': "Run Number",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [200,8000,1000,500,0,50],
#      'var': "primTrkdEdxs:runNumber",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
#    {
#      'name': "primTrkdEdxsVyFromCenter",
#      'xtitle': "Hit |y| [cm]",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [40,0,25,10000,0,50],
#      'var': "primTrkdEdxs:fabs(primTrkYs)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
#    {
#      'name': "primTrkdEdxsVzFromCenter",
#      'xtitle': "Hit |z-45| [cm]",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [40,0,50,10000,0,50],
#      'var': "primTrkdEdxs:fabs(primTrkZs-45.)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
    {
      'name': "hitYVhitX",
      'xtitle': "Hit x [cm]",
      'ytitle': "Hit y [cm]",
      'binning': [60,-5,55,60,-30,30],
      'var': "primTrkYs:primTrkXs",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
    {
      'name': "hitYVhitZ",
      'xtitle': "Hit z [cm]",
      'ytitle': "Hit y [cm]",
      'binning': [120,-10,110,60,-30,30],
      'var': "primTrkYs:primTrkZs",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
    {
      'name': "hitXVhitZ",
      'xtitle': "Hit z [cm]",
      'ytitle': "Hit x [cm]",
      'binning': [120,-10,110,60,-5,55],
      'var': "primTrkXs:primTrkZs",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
#    {
#      'name': "hitYVhitX_cosmicon",
#      'xtitle': "Hit x [cm]",
#      'ytitle': "Hit y [cm]",
#      'binning': [60,-5,55,60,-30,30],
#      'var': "primTrkYs:primTrkXs",
#      'cuts': "1"+"*(isMC || ((triggerBits >> 10) & 1))",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitYVhitZ_cosmicon",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit y [cm]",
#      'binning': [120,-10,110,60,-30,30],
#      'var': "primTrkYs:primTrkZs",
#      'cuts': "1"+"*(isMC || ((triggerBits >> 10) & 1))",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitXVhitZ_cosmicon",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit x [cm]",
#      'binning': [120,-10,110,60,-5,55],
#      'var': "primTrkXs:primTrkZs",
#      'cuts': "1"+"*(isMC || ((triggerBits >> 10) & 1))",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitXVhitZ_NotCosmicon",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit x [cm]",
#      'binning': [120,-10,110,60,-5,55],
#      'var': "primTrkXs:primTrkZs",
#      'cuts': "1"+"*(isMC || !((triggerBits >> 10) & 1))",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitYVhitZ_cosmic",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit y [cm]",
#      'binning': [120,-10,110,60,-30,30],
#      'var': "primTrkYs:primTrkZs",
#      'cuts': "1"+"*(isMC || ((triggerBits >> 11) & 1))",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitYVhitZ_beamon",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit y [cm]",
#      'binning': [120,-10,110,60,-30,30],
#      'var': "primTrkYs:primTrkZs",
#      'cuts': "1"+"*(isMC || ((triggerBits >> 4) & 1))",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitYVhitZ_pickytrack",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit y [cm]",
#      'binning': [120,-10,110,60,-30,30],
#      'var': "primTrkYs:primTrkZs",
#      'cuts': "1"+"*(isMC || nWCTracks > 0)",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "trueStartThetaVtrueStartPhi",
#      'xtitle': "True Start #phi [deg]",
#      'ytitle': "True Start #theta [deg]",
#      'binning': [90,-180,180,90,0,180],
#      'var': "trueStartTheta*180/pi:trueStartPhi*180/pi",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': False,
#    },
#    {
#      'name': "trueStartThetaYVtrueStartPhiZX",
#      'xtitle': "True Start #phi_{zx} [deg]",
#      'ytitle': "True Start #theta_{y} [deg]",
#      'binning': [90,-180,180,90,0,180],
#      'var': "acos(sin(trueStartTheta)*sin(trueStartPhi))*180/pi:atan2(sin(trueStartTheta)*cos(trueStartPhi),cos(trueStartTheta))*180./pi",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': False,
#    },
#    {
#      'name': "trueStartThetaXVtrueStartPhiZY",
#      'xtitle': "True Start #phi_{zy} [deg]",
#      'ytitle': "True Start #theta_{x} [deg]",
#      'binning': [90,-180,180,90,0,180],
#      'var': "acos(sin(trueStartTheta)*cos(trueStartPhi))*180/pi:atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180./pi",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': False,
#    },
#    {
#      'name': "primTrkdEdxsVprimTrkStartCosTheta",
#      'xtitle': "Primary TPC Track cos(#theta)",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [50,0,1,10000,0,50],
#      'var': "primTrkdEdxs:cos(primTrkStartTheta)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
#    {
#      'name': "primTrkdEdxsVprimTrkStartPhi",
#      'xtitle': "Primary TPC Track #phi",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [30,-180,180,10000,0,50],
#      'var': "primTrkdEdxs:primTrkStartPhi*180/pi",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
#    {
#      'name': "primTrkdEdxsVprimTrkStartCosThetaX",
#      'xtitle': "Primary TPC Track cos(#theta_{x})",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [50,0,1,10000,0,50],
#      'var': "primTrkdEdxs:sin(primTrkStartTheta)*cos(primTrkStartPhi)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': False,
#    },
#    {
#      'name': "primTrkdEdxsVprimTrkStartCosThetaX_zoom",
#      'xtitle': "Primary TPC Track cos(#theta_{x})",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [50,0,1,100,0,5],
#      'var': "primTrkdEdxs:sin(primTrkStartTheta)*cos(primTrkStartPhi)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': False,
#    },
#    {
#      'name': "primTrkdEdxsVprimTrkStartPhiZY",
#      'xtitle': "Primary TPC Track #phi_{zy}",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [60,-180,180,10000,0,50],
#      'var': "primTrkdEdxs:atan2(sin(primTrkStartTheta)*sin(primTrkStartPhi),cos(primTrkStartTheta))*180/pi",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': False,
#    },
#    {
#      'name': "primTrkdEdxsVprimTrkStartPhiZY_zoom",
#      'xtitle': "Primary TPC Track #phi_{zy}",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [60,-180,180,100,0,5],
#      'var': "primTrkdEdxs:atan2(sin(primTrkStartTheta)*sin(primTrkStartPhi),cos(primTrkStartTheta))*180/pi",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': False,
#    },
#    {
#      'name': "primTrkdEdxsVprimTrkStartPhiZY_zoom_logy",
#      'xtitle': "Primary TPC Track #phi_{zy}",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [60,-180,180,100,0,5],
#      'var': "primTrkdEdxs:atan2(sin(primTrkStartTheta)*sin(primTrkStartPhi),cos(primTrkStartTheta))*180/pi",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
#    {
#      'name': "primTrkdEdxsVprimTrkStartCosThetaY",
#      'xtitle': "Primary TPC Track cos(#theta_{y})",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [50,0,1,10000,0,50],
#      'var': "primTrkdEdxs:sin(primTrkStartTheta)*sin(primTrkStartPhi)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
    {
      'name': "primTrkdEdxsVprimTrkStartPhiZX",
      'xtitle': "Primary TPC Track #phi_{zx}",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [30,-180,180,10000,0,50],
      'var': "primTrkdEdxs:atan2(sin(primTrkStartTheta)*cos(primTrkStartPhi),cos(primTrkStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': True,
    },
  ]

  hists = plotOneHistOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_")
  outfile = root.TFile("cosmics_hists.root","recreate")
  outfile.cd()
  for var in hists:
    for ds in hists[var]:
        newname = var+"_"+ds
        hist = hists[var][ds]
        hist.SetName(newname)
        hist.Print()
        hist.Write()
  outfile.Close()

######################################################################################
######################################################################################
######################################################################################
######################################################################################

  histConfigs = [
    {
      'name': "primTrkdEdxs",
      "title": "Reco",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [400,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkTruedEdxs",
      "title": "MC Truth",
      'xtitle': "Primary TPC Track True dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [400,0,50],
      'var': "primTrkTruedEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primMCdEdxs",
      "title": "MC Trajectory",
      'xtitle': "Primary TPC Track True dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [400,0,50],
      'var': "primMCdEdxs",
      'cuts': weightStr+"*(primMCXs>2. && primMCXs < 47. && primMCYs > -23. && primMCYs < 23. && primMCZs > 0. && primMCZs < 90 && primMClastXs>2. && primMClastXs < 47. && primMClastYs > -23. && primMClastYs < 23. && primMClastZs > 0. && primMClastZs < 90 )",
      #'normalize': True,
      'logy': logy,
    },
  ]
  for i in range(len(histConfigs)):
    histConfigs[i]["color"] = COLORLIST[i]
#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="CosmicsTrue_dEdx")

  histConfigs = [
    {
      'name': "primTrkdEdxs_zoom",
      "title": "Reco",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,10],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkTruedEdxs_zoom",
      "title": "MC Truth",
      'xtitle': "Primary TPC Track True dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,10],
      'var': "primTrkTruedEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primMCdEdxs_zoom",
      "title": "MC Trajectory",
      'xtitle': "Primary TPC Track True dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,10],
      'var': "primMCdEdxs",
      'cuts': weightStr+"*(primMCXs>2. && primMCXs < 47. && primMCYs > -23. && primMCYs < 23. && primMCZs > 0. && primMCZs < 90 && primMClastXs>2. && primMClastXs < 47. && primMClastYs > -23. && primMClastYs < 23. && primMClastZs > 0. && primMClastZs < 90 )",
      #'normalize': True,
      'logy': logy,
    },
  ]
  for i in range(len(histConfigs)):
    histConfigs[i]["color"] = COLORLIST[i]
#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="CosmicsTrue_dEdxZoom")

  histConfigs = [
    {
      'name': "primTrkdQdxs_zoom",
      'title': "Reco [10.8*ADC/cm]",
      'xtitle': "Primary TPC Track dQ/dx",# [10*ADC/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,1e5],
      'var': "10.8*primTrkdQdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkTruedQdxs_zoom",
      'title': "MC Truth [e^{-}/cm]",
      'xtitle': "Primary TPC Track True dQ/dx",# [e^{-}/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,1e5],
      'var': "primTrkTruedQdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
  ]
  for i in range(len(histConfigs)):
    histConfigs[i]["color"] = COLORLIST[i]
#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="CosmicsTrue_dQdxZoom")

  histConfigs = [
    {
      'name': "primTrkZs",
      "title": "All",
      'xtitle': "Primary TPC Track Hit Y [cm]",
      'ytitle': "Events / bin",
      'binning': [100,-25,25],
      'var': "primTrkYs",
      'cuts': "",
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkZs",
      "title": "Top",
      'xtitle': "Primary TPC Track Hit Y [cm]",
      'ytitle': "Events / bin",
      'binning': [100,-25,25],
      'var': "primTrkYs",
      'cuts': "enterExitYp",
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkZs",
      "title": "Bottom",
      'xtitle': "Primary TPC Track Hit Y [cm]",
      'ytitle': "Events / bin",
      'binning': [100,-25,25],
      'var': "primTrkYs",
      'cuts': "enterExitYm",
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkZs",
      "title": "Top && Bottom",
      'xtitle': "Primary TPC Track Hit Y [cm]",
      'ytitle': "Events / bin",
      'binning': [100,-25,25],
      'var': "primTrkYs",
      'cuts': "enterExitYm*enterExitYp",
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkZs",
      "title": "Top && Through Wires",
      'xtitle': "Primary TPC Track Hit Y [cm]",
      'ytitle': "Events / bin",
      'binning': [100,-25,25],
      'var': "primTrkYs",
      'cuts': "enterExitXm",
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkZs",
      "title": "Top && Through Cathode",
      'xtitle': "Primary TPC Track Hit Y [cm]",
      'ytitle': "Events / bin",
      'binning': [100,-25,25],
      'var': "primTrkYs",
      'cuts': "enterExitXp",
      #'normalize': True,
      'logy': logy,
    },
  ]
  for i in range(len(histConfigs)):
    histConfigs[i]["color"] = COLORLIST[i]
  #plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_Ys")

  histConfigs = [
    {
      "title": "All",
      'xtitle': "True Muon Initial Momentum [MeV]",
      'ytitle': "Events / MeV",
      'binning': getLogBins(20,100,10000),
      'var': "trueStartMom",
      'cuts': "",
      #'normalize': True,
      'logy': logy,
      'logx': True,
      'normToBinWidth': True,
    },
    {
      "title": "Top",
      'xtitle': "True Muon Initial Momentum [MeV]",
      'ytitle': "Events / MeV",
      'binning': getLogBins(20,100,10000),
      'var': "trueStartMom",
      'cuts': "enterExitYp",
      #'normalize': True,
      'logy': logy,
      'logx': True,
      'normToBinWidth': True,
    },
    {
      "title": "Bottom",
      'xtitle': "True Muon Initial Momentum [MeV]",
      'ytitle': "Events / MeV",
      'binning': getLogBins(20,100,10000),
      'var': "trueStartMom",
      'cuts': "enterExitYm",
      #'normalize': True,
      'logy': logy,
      'logx': True,
      'normToBinWidth': True,
    },
    {
      "title": "Top && Bottom",
      'xtitle': "True Muon Initial Momentum [MeV]",
      'ytitle': "Events / MeV",
      'binning': getLogBins(20,100,10000),
      'var': "trueStartMom",
      'cuts': "enterExitYm*enterExitYp",
      #'normalize': True,
      'logy': logy,
      'logx': True,
      'normToBinWidth': True,
    },
    {
      "title": "Top && Through Wires",
      'xtitle': "True Muon Initial Momentum [MeV]",
      'ytitle': "Events / MeV",
      'binning': getLogBins(20,100,10000),
      'var': "trueStartMom",
      'cuts': "enterExitXm",
      #'normalize': True,
      'logy': logy,
      'logx': True,
      'normToBinWidth': True,
    },
    {
      "title": "Top && Through Cathode",
      'xtitle': "True Muon Initial Momentum [MeV]",
      'ytitle': "Events / MeV",
      'binning': getLogBins(20,100,10000),
      'var': "trueStartMom",
      'cuts': "enterExitXp",
      #'normalize': True,
      'logy': logy,
      'logx': True,
      'normToBinWidth': True,
    },
  ]
  for i in range(len(histConfigs)):
    histConfigs[i]["color"] = COLORLIST[i]
#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_trueStartMom")

  histConfigs = [
    {
      "title": "All",
      'xtitle': "Primary TPC Track Length [cm]",
      'ytitle': "Events / bin",
      'binning': [60,0,60],
      'var': "primTrkLength",
      'cuts': "",
      #'normalize': True,
      'logy': logy,
    },
    {
      "title": "Top",
      'xtitle': "Primary TPC Track Length [cm]",
      'ytitle': "Events / bin",
      'binning': [60,0,60],
      'var': "primTrkLength",
      'cuts': "enterExitYp",
      #'normalize': True,
      'logy': logy,
    },
    {
      "title": "Bottom",
      'xtitle': "Primary TPC Track Length [cm]",
      'ytitle': "Events / bin",
      'binning': [60,0,60],
      'var': "primTrkLength",
      'cuts': "enterExitYm",
      #'normalize': True,
      'logy': logy,
    },
    {
      "title": "Top && Bottom",
      'xtitle': "Primary TPC Track Length [cm]",
      'ytitle': "Events / bin",
      'binning': [60,0,60],
      'var': "primTrkLength",
      'cuts': "enterExitYm*enterExitYp",
      #'normalize': True,
      'logy': logy,
    },
    {
      "title": "Top && Through Wires",
      'xtitle': "Primary TPC Track Length [cm]",
      'ytitle': "Events / bin",
      'binning': [60,0,60],
      'var': "primTrkLength",
      'cuts': "enterExitXm",
      #'normalize': True,
      'logy': logy,
    },
    {
      "title": "Top && Through Cathode",
      'xtitle': "Primary TPC Track Length [cm]",
      'ytitle': "Events / bin",
      'binning': [60,0,60],
      'var': "primTrkLength",
      'cuts': "enterExitXp",
      #'normalize': True,
      'logy': logy,
    },
  ]
  for i in range(len(histConfigs)):
    histConfigs[i]["color"] = COLORLIST[i]
#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_primTrkLength")

##################################################
##################################################
##################################################

  histConfigs = [
    {
      'title': "All",
      'cuts': "( iBestMatch >= 0)",
    },
    {
      'title': "Hit Cosmic 1",
      'cuts': "( iBestMatch >= 0)*trueHitCosmic1",
    },
    {
      'title': "Hit Cosmic 2",
      'cuts': "( iBestMatch >= 0)*trueHitCosmic2",
    },
    {
      'title': "Hit Cosmic 3",
      'cuts': "( iBestMatch >= 0)*trueHitCosmic3",
    },
    {
      'title': "Hit Cosmic 4",
      'cuts': "( iBestMatch >= 0)*trueHitCosmic4",
    },
    {
      'title': "Hit Cosmic 1 & 2",
      'cuts': "( iBestMatch >= 0)*trueHitCosmic1*trueHitCosmic2",
    },
    {
      'title': "Hit Cosmic 3 & 4",
      'cuts': "( iBestMatch >= 0)*trueHitCosmic3*trueHitCosmic4",
    },
  ]
  for i in range(len(histConfigs)):
    histConfigs[i]["color"] = COLORLIST[i]

  for i in range(len(histConfigs)):
    histConfigs[i].update(
      {
        'xtitle': "Muon True Initial Energy [GeV]",
        'ytitle': "Events / bin",
        'binning': [100,0,300],
        'var': "1e-3*trueStartE",
        #'normalize': True,
        'logy': logy,
      },
    )
  plotManyHistsOnePlot([x for x in fileConfigs if not x["isData"]],histConfigs,
        c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_paddles_trueStartE")

  for i in range(len(histConfigs)):
    histConfigs[i].update(
      {
        'xtitle': "Muon True Initial Energy [GeV]",
        'ytitle': "Events / bin",
        'binning': [40,0,10],
        'var': "1e-3*trueStartE",
        'normalize': False,
        'logy': False,
      },
    )
  plotManyHistsOnePlot([x for x in fileConfigs if not x["isData"]],histConfigs[1:],
        c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_paddles_trueStartE_zoom")

  for i in range(len(histConfigs)):
    histConfigs[i].update(
      {
        'xtitle': "Muon True Initial Energy [MeV]",
        'ytitle': "Events / bin",
        'binning': [40,0,10],
        'var': "1e-3*trueStartE",
        'normalize': False,
        'logy': True,
      },
    )
  plotManyHistsOnePlot([x for x in fileConfigs if not x["isData"]],histConfigs,
        c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_paddles_trueStartE_zoom_logy")

  for i in range(len(histConfigs)):
    histConfigs[i].update(
      {
        'xtitle': "Muon True Initial Energy [MeV]",
        'ytitle': "Normalized Events / bin",
        'binning': [40,0,10],
        'var': "1e-3*trueStartE",
        'normalize': True,
        'logy': False,
      },
    )
  plotManyHistsOnePlot([x for x in fileConfigs if not x["isData"]],histConfigs,
        c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_paddles_trueStartE_zoom_norm")

  for i in range(len(histConfigs)):
    histConfigs[i].update(
      {
        'xtitle': "Primary TPC Track #phi_{zx} [deg]",
        'ytitle': "Events / bin",
        'binning': [90,-180,180],
        'var': "atan2(sin(primTrkStartTheta)*cos(primTrkStartPhi),cos(primTrkStartTheta))*180./pi",
        #'normalize': True,
        'logy': logy,
      },
    )
  plotManyHistsOnePlot([x for x in fileConfigs if not x["isData"]],histConfigs,
        c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_paddles_primTrkStartPhiZX")

  for i in range(len(histConfigs)):
    histConfigs[i].update(
      {
        'xtitle': "Primary TPC Track #theta_{y} [deg]",
        'ytitle': "Events / bin",
        'binning': [90,0,180],
        'var': "acos(sin(primTrkStartTheta)*sin(primTrkStartPhi))*180./pi",
        #'normalize': True,
        'logy': logy,
      },
    )
  plotManyHistsOnePlot([x for x in fileConfigs if not x["isData"]],histConfigs,
        c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_paddles_primTrkStartThetaY")
