#!/usr/bin/env python

import ROOT as root
from helpers import *
root.gROOT.SetBatch(True)

if __name__ == "__main__":

  c = root.TCanvas()
  NMAX=10000000000
  #NMAX=10000
  fileConfigs = [
    {
      'fn': "anaTree_data_Lovely1_Pos_RunI_elanag_v02_v01.root",
      #'addFriend': ["friend","friendTree_data_Lovely1_Pos_RunI_elanag_v02_v01.root"],
      #'fn': "anaTree_data_runI_pos_v0.1.root",
      #'addFriend': ["friend","friendTree_data_runI_pos_v0.1.root"],
      'name': "RunI_Pos",
      'title': "Run I Pos. Polarity",
      'caption': "Run I Pos. Polarity",
      'color': root.kBlack,
    },
#    {
#      'fn': "anaTree_data_Lovely1_Pos_RunII_elanag_v02_v01.root",
#      #'addFriend': ["friend","friendTree_data_Lovely1_Pos_RunI_elanag_v02_v01.root"],
#      #'fn': "anaTree_data_runI_pos_v0.1.root",
#      #'addFriend': ["friend","friendTree_data_runI_pos_v0.1.root"],
#      'name': "RunII_Pos",
#      'title': "Run II Pos. Polarity",
#      'caption': "Run II Pos. Polarity",
#      'color': root.kBlue,
#    },
#    {
#      'fn': "beamline_run4295_4of5.root",
#      'name': "Run4295",
#      'title': "Run 4295",
#      'caption': "Run 4295",
#      'color': root.kGreen+1,
#    },
    {
      'fn': "BeamLineAnaTree_data_Lovely1_Neg_Run1_elenag_v02_v01.root",
      #'fn': "anaTree_runI_neg_1k.root",
      #'addFriend': ["friend","friendTree_data_Lovely1_Pos_RunI_elanag_v02_v01.root"],
      'name': "RunI_Neg",
      'title': "Run I Neg. Polarity",
      'caption': "Run I Neg. Polarity",
      'color': root.kBlue,
    },
#    {
#      'fn': "anaTree_runII_neg_test.root",
#      #'fn': "anaTree_runII_neg_200.root",
#      #'addFriend': ["friend","friendTree_data_Lovely1_Pos_RunI_elanag_v02_v01.root"],
#      'name': "RunII_Neg",
#      'title': "Run II Neg. Polarity",
#      'caption': "Run II Neg. Polarity",
#      'color': root.kRed,
#    },
  ]

  histConfigs = [
    {
      'name': "runNumber",
      'xtitle': "Run Number",
      'ytitle': "Events / bin",
      'binning': [1000,5500,6500],
      'var': "run",
      'cuts': "",
    },
    {
      'name': "nwctrks",
      'xtitle': "Number of Wire Chamber Tracks",
      'ytitle': "Events / bin",
      'binning': [11,-0.5,10.5],
      'var': "nwctrks",
      'cuts': "",
      'logy': True,
    },
    {
      'name': "ntof",
      'xtitle': "Number of Time of Flight Objects",
      'ytitle': "Events / bin",
      'binning': [11,-0.5,10.5],
      'var': "ntof",
      'cuts': "",
      'logy': True,
    },
    {
      'name': "nAG",
      'xtitle': "Number of Aerogel Counter Objects",
      'ytitle': "Events / bin",
      'binning': [11,-0.5,10.5],
      'var': "nAG",
      'cuts': "",
      'logy': True,
    },
    {
      'name': "ntracks_reco",
      'xtitle': "Number Reconstructed TPC Tracks",
      'ytitle': "Events / bin",
      'binning': [31,-0.5,30.5],
      'var': "ntracks_reco",
      'cuts': "",
      'logy': True,
    },
    {
      'name': "nclus",
      'xtitle': "Number Reconstructed TPC Clusters",
      'ytitle': "Events / bin",
      'binning': [51,-0.5,51.5],
      'var': "nclus",
      'cuts': "",
      'logy': True,
    },
    {
      'name': "nhits",
      'xtitle': "Number Reconstructed TPC Hits",
      'ytitle': "Events / bin",
      'binning': [100,0,10000],
      'var': "nhits",
      'cuts': "",
      'logy': True,
    },
    {
      'name': "wctrk_XFaceCoor",
      'xtitle': "x Coordinate of WC Track Extrapolated to TPC [cm]",
      'ytitle': "Tracks / bin",
      'binning': [600,-100,500],
      'var': "wctrk_XFaceCoor",
      'cuts': "",
    },
    {
      'name': "wctrk_YFaceCoor",
      'xtitle': "y Coordinate of WC Track Extrapolated to TPC [cm]",
      'ytitle': "Tracks / bin",
      'binning': [200,-100,100],
      'var': "wctrk_YFaceCoor",
      'cuts': "",
    },
    {
      'name': "wctrk_XYFace",
      'xtitle': "WC Track X Position on Front of TPC [cm]",
      'ytitle': "WC Track Y Position on Front of TPC [cm]",
      'binning': [600,-100,500,200,-100,100],
      'var': "wctrk_YFaceCoor:wctrk_XFaceCoor",
      'cuts': "",
    },
    {
      'name': "wctrk_theta",
      'xtitle': "WC Track #theta [deg]",
      'ytitle': "Tracks / bin",
      'binning': [80,-20,20],
      'var': "wctrk_theta*180/pi",
      'cuts': "",
    },
    {
      'name': "wctrk_phi",
      'xtitle': "WC Track #phi [deg]",
      'ytitle': "Tracks / bin",
      'binning': [180,-180,180],
      'var': "wctrk_phi*180/pi",
      'cuts': "",
    },
    {
      'name': "wctrk_momentum",
      'xtitle': "WC Track Momentum [MeV/c]",
      'ytitle': "Tracks / bin",
      'binning': [200,0,2000],
      'var': "wctrk_momentum",
      'cuts': "",
    },
    {
      'name': "tofObject",
      'xtitle': "Time of Flight [ns]",
      'ytitle': "TOF / bin",
      'binning': [296,18,55],
      'var': "tofObject",
      'cuts': "",
    },
    {
      'name': "tofObject_wide",
      'xtitle': "Time of Flight [ns]",
      'ytitle': "TOF / bin",
      'binning': [400,0,100],
      'var': "tofObject",
      'cuts': "",
    },
    {
      'name': "tof_timestamp",
      'xtitle': "Time of Flight Timestamp [ns]",
      'ytitle': "TOF / bin",
      'binning': [2000,-5e5,5e5],
      'var': "tof_timestamp",
      'cuts': "",
    },
    {
      'name': "tofVP_wide",
      'ytitle': "Time of Flight [ns]",
      'xtitle': "WC Track Momentum [MeV/c]",
      'binning': [100,0,2000.,100,0,100],
      'var': "tofObject[0]:wctrk_momentum[0]",
      'cuts': "ntof == 1 && nwctrks == 1",
    },
    {
      'name': "tofVP",
      'ytitle': "Time of Flight [ns]",
      'xtitle': "WC Track Momentum [MeV/c]",
      'binning': [200,250,1250.,148,18,55],
      'var': "tofObject[0]:wctrk_momentum[0]",
      'cuts': "ntof == 1 && nwctrks == 1",
    },
    {
      'name': "tof2p2Vp2",
      'ytitle': "TOF^{2}p^{2} [(ns)^{2} (MeV/c)^{2}]",
      'xtitle': "p^{2} [(MeV/c)^{2}]",
      'binning': [200,0,2e6,200,0,1e9],
      'var': "tofObject[0]*tofObject[0]*wctrk_momentum[0]*wctrk_momentum[0]:wctrk_momentum[0]*wctrk_momentum[0]",
      'cuts': "ntof == 1 && nwctrks == 1",
    },
    {
      'name': "tof2p2Vp2_toflt27",
      'ytitle': "TOF^{2}p^{2} [(ns)^{2} (MeV/c)^{2}]",
      'xtitle': "p^{2} [(MeV/c)^{2}]",
      'binning': [200,0,2e6,200,0,1e9],
      'var': "tofObject[0]*tofObject[0]*wctrk_momentum[0]*wctrk_momentum[0]:wctrk_momentum[0]*wctrk_momentum[0]",
      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]<27.",
    },
    {
      'name': "tof2p2Vp2_tofgeq27",
      'ytitle': "TOF^{2}p^{2} [(ns)^{2} (MeV/c)^{2}]",
      'xtitle': "p^{2} [(MeV/c)^{2}]",
      'binning': [200,0,2e6,200,0,1e9],
      'var': "tofObject[0]*tofObject[0]*wctrk_momentum[0]*wctrk_momentum[0]:wctrk_momentum[0]*wctrk_momentum[0]",
      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]>=27.",
    },
    {
      'name': "mass2",
      'xtitle': "m^{2} [MeV^{2}]",
      'ytitle': "Events / bin",
      'binning': [2000,-2.5e5,2.5e5],
      'var': "wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.)",
      'cuts': "ntof == 1 && nwctrks == 1",
      'captionleft1': "6.684 m",
      'drawvlines': [105.658**2,139.570**2,493.667**2,938.272**2]
    },
    {
      'name': "mass2Vp",
      'xtitle': "WC Track Momentum [MeV/c]",
      'ytitle': "m^{2} [MeV^{2}]",
      'binning': [50,0,2000,50,-2.5e5,2.5e5],
      'var': "wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.):wctrk_momentum[0]",
      'cuts': "ntof == 1 && nwctrks == 1",
      'drawhlines': [105.658**2,139.570**2,493.667**2,938.272**2],
      'profileXtoo': True,
    },
    {
      'name': "mass2Vp_toflt26",
      'xtitle': "WC Track Momentum [MeV/c]",
      'ytitle': "m^{2} [MeV^{2}]",
      'binning': [50,0,2000,50,-2.5e5,2.5e5],
      'var': "wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.):wctrk_momentum[0]",
      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0] < 26.",
      'captionleft1': "TOF < 26 ns",
      'drawhlines': [105.658**2,139.570**2,493.667**2,938.272**2],
      'profileXtoo': True,
    },
    {
      'name': "mass2Vp2",
      'xtitle': "(WC Track Momentum)^{2} [(MeV/c)^{2}]",
      'ytitle': "m^{2} [MeV^{2}]",
      'binning': [50,0,2e6,50,-2.5e5,2.5e5],
      'var': "wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.):wctrk_momentum[0]*wctrk_momentum[0]",
      'cuts': "ntof == 1 && nwctrks == 1",
      'drawhlines': [105.658**2,139.570**2,493.667**2,938.272**2],
      'profileXtoo': True,
    },
    {
      'name': "mass2Vp2_toflt26",
      'xtitle': "(WC Track Momentum)^{2} [(MeV/c)^{2}]",
      'ytitle': "m^{2} [MeV^{2}]",
      'binning': [50,0,2e6,50,-2.5e5,2.5e5],
      'var': "wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.):wctrk_momentum[0]*wctrk_momentum[0]",
      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0] < 26.",
      'captionleft1': "TOF < 26 ns",
      'drawhlines': [105.658**2,139.570**2,493.667**2,938.272**2],
      'profileXtoo': True,
    },
    {
      'name': "mass",
      'xtitle': "m [MeV]",
      'ytitle': "Events / bin",
      'binning': [150,0.,1500],
      'var': "sqrt(wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.))",
      'cuts': "ntof == 1 && nwctrks == 1 && (wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.)) > 0.",
      'captionright1': "6.684 m",
      'drawvlines': [105.658,139.570,493.667,938.272]
    },
    {
      'name': "massVp",
      'xtitle': "WC Track Momentum [MeV/c]",
      'ytitle': "m [MeV]",
      'binning': [50,0,2000,50,0.,1500],
      'var': "sqrt(wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.)):wctrk_momentum[0]",
      'cuts': "ntof == 1 && nwctrks == 1 && (wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.)) > 0.",
      'captionright1': "6.684 m",
      'drawhlines': [105.658,139.570,493.667,938.272]
    },
    {
      'name': "massVp_toflt26",
      'xtitle': "WC Track Momentum [MeV/c]",
      'ytitle': "m [MeV]",
      'binning': [50,0,2000,50,0.,1500],
      'var': "sqrt(wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.)):wctrk_momentum[0]",
      'cuts': "ntof == 1 && nwctrks == 1 && (wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.)) > 0. && tofObject[0]<26.",
      'captionright1': "6.684 m",
      'drawhlines': [105.658,139.570,493.667,938.272],
      'profileXtoo': True,
    },
    {
      'name': "massVp_toflt26",
      'xtitle': "WC Track Momentum [MeV/c]",
      'ytitle': "m [MeV]",
      'binning': [50,0,2000,50,0.,1500],
      'var': "sqrt(wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.)):wctrk_momentum[0]",
      'cuts': "ntof == 1 && nwctrks == 1 && (wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.)) > 0. && tofObject[0]<26.",
      'captionright1': "6.684 m",
      'captionleft1': "TOF < 26 ns",
      'drawhlines': [105.658,139.570,493.667,938.272],
      'profileXtoo': True,
    },
  ]

  plotOneHistOnePlot(fileConfigs,histConfigs,c,"anatree/anatree",nMax=NMAX)

#  histConfigs = [
#    {
#      'name': "dmpi",
#      'title': "m_{#pi}",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'binning': [200,0,1200,200,5,10],
#      'var': "0.299*tofObject[0]*wctrk_momentum[0]*pow(wctrk_momentum[0]*wctrk_momentum[0]+19488.16,-0.5):wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]<27.",
#      'profileXtoo':True,
#    },
#    {
#      'name': "dmmu",
#      'title': "m_{#mu}",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'binning': [200,0,1200,200,5,10],
#      'var': "0.299*tofObject[0]*wctrk_momentum[0]*pow(wctrk_momentum[0]*wctrk_momentum[0]+11161.92,-0.5):wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]<27.",
#      'profileXtoo':True,
#    },
#    {
#      'name': "dm0",
#      'title': "m=0",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'binning': [200,0,1200,200,5,10],
#      'var': "0.299*tofObject[0]:wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]<27.",
#      'profileXtoo':True,
#    },
#    {
#      'name': "dmp",
#      'title': "m_{p}",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'binning': [200,0,1200,200,5.,10],
#      'var': "0.299*tofObject[0]*wctrk_momentum[0]*pow(wctrk_momentum[0]*wctrk_momentum[0]+880406.89,-0.5):wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]>=27.",
#      'profileXtoo':True,
#    },
#    {
#      'name': "dmk",
#      'title': "m_{K}",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'binning': [200,0,1200,200,5,10],
#      'var': "0.299*tofObject[0]*wctrk_momentum[0]*pow(wctrk_momentum[0]*wctrk_momentum[0]+243707.1,-0.5):wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1",
#      'profileXtoo':True,
#    },
#  ]
#  plotOneHistOnePlot(fileConfigs,histConfigs,c,"anatree/anatree",nMax=NMAX,outPrefix="TOF_")
#
#  histConfigs = [
#    {
#      'name': "dmpi",
#      'title': "m_{#pi}",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'ylim': [5.,9.],
#      'binning': [200,0,1200,200,5,10],
#      'var': "0.299*tofObject[0]*wctrk_momentum[0]*pow(wctrk_momentum[0]*wctrk_momentum[0]+19488.16,-0.5):wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]<27.",
#      'profileX':True,
#      'color': root.kBlue,
#      'drawhlines': [6.684]
#    },
#    {
#      'name': "dmmu",
#      'title': "m_{#mu}",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'binning': [200,0,1200,200,5,10],
#      'var': "0.299*tofObject[0]*wctrk_momentum[0]*pow(wctrk_momentum[0]*wctrk_momentum[0]+11161.92,-0.5):wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]<27.",
#      'profileX':True,
#      'color': root.kMagenta,
#    },
#    {
#      'name': "dm0",
#      'title': "m=0",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'binning': [200,0,1200,200,5,10],
#      'var': "0.299*tofObject[0]:wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]<27.",
#      'profileX':True,
#      'color': root.kGreen+1,
#    },
#    {
#      'name': "dmp",
#      'title': "m_{p}",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'binning': [200,0,1200,200,5.,10],
#      'var': "0.299*tofObject[0]*wctrk_momentum[0]*pow(wctrk_momentum[0]*wctrk_momentum[0]+880406.89,-0.5):wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]>=27. && wctrk_momentum[0]>500. && wctrk_momentum[0]<1000.",
#      'profileX':True,
#      'color': root.kRed,
#    },
#    #{
#    #  'name': "dmk",
#    #  'title': "m_{K}",
#    #  'xtitle': "p [MeV/c]",
#    #  'ytitle': "d [m]",
#    #  'binning': [200,0,1200,200,5,10],
#    #  'var': "0.299*tofObject[0]*wctrk_momentum[0]*pow(wctrk_momentum[0]*wctrk_momentum[0]+243707.1,-0.5):wctrk_momentum[0]",
#    #  'cuts': "ntof == 1 && nwctrks == 1",
#    #  'profileX':True,
#    #  'color': root.kOrange-3,
#    #},
#  ]
#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"anatree/anatree",nMax=NMAX,outPrefix="TOF_")
#
#  histConfigs = [
#    {
#      'name': "dmpi",
#      'title': "m_{#pi}",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'ylim': [6.,8.],
#      'binning': [200,0,1200,200,5,10],
#      'var': "0.299*tofObject[0]*wctrk_momentum[0]*pow(wctrk_momentum[0]*wctrk_momentum[0]+19488.16,-0.5):wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]<27.",
#      'profileX':True,
#      'color': root.kBlue,
#      'drawhlines': [6.684]
#    },
#    {
#      'name': "dmmu",
#      'title': "m_{#mu}",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'binning': [200,0,1200,200,5,10],
#      'var': "0.299*tofObject[0]*wctrk_momentum[0]*pow(wctrk_momentum[0]*wctrk_momentum[0]+11161.92,-0.5):wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]<27.",
#      'profileX':True,
#      'color': root.kMagenta,
#    },
#    {
#      'name': "dm0",
#      'title': "m=0",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'binning': [200,0,1200,200,5,10],
#      'var': "0.299*tofObject[0]:wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]<27.",
#      'profileX':True,
#      'color': root.kGreen+1,
#    },
#    {
#      'name': "dmp",
#      'title': "m_{p}",
#      'xtitle': "p [MeV/c]",
#      'ytitle': "d [m]",
#      'binning': [200,0,1200,200,5.,10],
#      'var': "0.299*tofObject[0]*wctrk_momentum[0]*pow(wctrk_momentum[0]*wctrk_momentum[0]+880406.89,-0.5):wctrk_momentum[0]",
#      'cuts': "ntof == 1 && nwctrks == 1 && tofObject[0]>=27. && wctrk_momentum[0]>500. && wctrk_momentum[0]<1000.",
#      'profileX':True,
#      'color': root.kRed,
#    },
#    #{
#    #  'name': "dmk",
#    #  'title': "m_{K}",
#    #  'xtitle': "p [MeV/c]",
#    #  'ytitle': "d [m]",
#    #  'binning': [200,0,1200,200,5,10],
#    #  'var': "0.299*tofObject[0]*wctrk_momentum[0]*pow(wctrk_momentum[0]*wctrk_momentum[0]+243707.1,-0.5):wctrk_momentum[0]",
#    #  'cuts': "ntof == 1 && nwctrks == 1",
#    #  'profileX':True,
#    #  'color': root.kOrange-3,
#    #},
#  ]
#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"anatree/anatree",nMax=NMAX,outPrefix="TOF_fine_")

  histConfigs = [
    {
      'name': "mass",
      'title': "|m| = Re(m) + Im(m)",
      'xtitle': "m [MeV]",
      'ytitle': "Events / bin",
      'binning': [150,0.,1500],
      'var': "sqrt(wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.))",
      'cuts': "ntof == 1 && nwctrks == 1",
      'captionleft1': "6.684 m",
      'drawvlines': [105.658,139.570,493.667,938.272]
    },
    {
      'name': "mass",
      'title': "Re(m)",
      'xtitle': "m [MeV]",
      'ytitle': "Events / bin",
      'binning': [150,0.,1500],
      'var': "sqrt(wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.))",
      'cuts': "ntof == 1 && nwctrks == 1 && (wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.)) > 0.",
      'color': root.kGreen+1,
      'captionleft1': "6.684 m",
    },
    {
      'name': "mass",
      'title': "Im(m)",
      'xtitle': "m [MeV]",
      'ytitle': "Events / bin",
      'binning': [150,0.,1500],
      'var': "sqrt(wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.))",
      'cuts': "ntof == 1 && nwctrks == 1 && (wctrk_momentum[0]*wctrk_momentum[0] * (tofObject[0]*tofObject[0]*0.299*0.299/6.684/6.684 - 1.)) < 0.",
      'color': root.kRed,
      'captionleft1': "6.684 m",
    },
  ]
  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"anatree/anatree",nMax=NMAX,outPrefix="masses_")

