#!/usr/bin/env python

import ROOT as root
from helpers import *
root.gROOT.SetBatch(True)

if __name__ == "__main__":

  weightStr = "pzWeight"
  logy = False

  c = root.TCanvas()
  NMAX=10000000000
  #NMAX=100
  fileConfigs = [
    {
      'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/piAbsSelector/lariat_data_Lovely1_Pos_RunI_elanag_v02_v03/anahist.root",
      'addFriend': ["friend", "friendTree_Pos_RunI_v3.root"],
      #'fn': "/lariat/app/users/jhugon/lariatsoft_v06_15_00/srcs/lariatsoft/JobConfigurations/data_Pos_RunI_piAbsSelector.root",
      'name': "RunI_Pos",
      'title': "Run I Pos. Polarity",
      'caption': "Run I Pos. Polarity",
      'color': root.kBlack,
    },
    #{
    #  'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/piAbsSelector/lariat_PiAbsAndChEx_flat_pip_v3/anahist.root",
    #  'addFriend': ["friend", "friendTree_pip_v3.root"],
    #  #'fn': "/lariat/app/users/jhugon/lariatsoft_v06_15_00/srcs/lariatsoft/JobConfigurations/pip_piAbsSelector.root",
    #  'name': "pip",
    #  'title': "#pi^{+} MC",
    #  'caption': "#pi^{+} MC",
    #  'color': root.kBlue,
    #  'scaleFactor': 0.28946*1.888,
    #  #'scaleFactor': 1275.21,
    #},
    {
      'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/piAbsSelector/lariat_PiAbsAndChEx_flat_p_v3/anahist.root",
      'addFriend': ["friend", "friendTree_p_v3.root"],
      #'fn': "/lariat/app/users/jhugon/lariatsoft_v06_15_00/srcs/lariatsoft/JobConfigurations/p_piAbsSelector.root",
      'name': "p",
      'title': "proton MC",
      'caption': "proton MC",
      'color': root.kRed,
      'scaleFactor': 1.0587,
      #'scaleFactor': 1e4*0.19955,
    },
    #{
    #  'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/piAbsSelector/lariat_PiAbsAndChEx_flat_ep_v3/anahist.root",
    #  'addFriend': ["friend", "friendTree_ep_v3.root"],
    #  #'fn': "/lariat/app/users/jhugon/lariatsoft_v06_15_00/srcs/lariatsoft/JobConfigurations/ep_piAbsSelector.root",
    #  'name': "ep",
    #  'title': "e^{+} MC",
    #  'caption': "e^{+} MC",
    #  'color': root.kGreen+1,
    #  'scaleFactor': 1e4,
    #},
    #{
    #  'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/piAbsSelector/lariat_PiAbsAndChEx_flat_mup_v3/anahist.root",
    #  'addFriend': ["friend", "friendTree_mup_v3.root"],
    #  #'fn': "/lariat/app/users/jhugon/lariatsoft_v06_15_00/srcs/lariatsoft/JobConfigurations/mup_piAbsSelector.root",
    #  'name': "mup",
    #  'title': "#mu^{+} MC",
    #  'caption': "#mu^{+} MC",
    #  'color': root.kCyan,
    #  'scaleFactor': 1e4,
    #},
    #{
    #  'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/piAbsSelector/lariat_PiAbsAndChEx_flat_kp_v3/anahist.root",
    #  'addFriend': ["friend", "friendTree_kp_v3.root"],
    #  #'fn': "/lariat/app/users/jhugon/lariatsoft_v06_15_00/srcs/lariatsoft/JobConfigurations/kp_piAbsSelector.root",
    #  'name': "kp",
    #  'title': "K^{+} MC",
    #  'caption': "K^{+} MC",
    #  'color': root.kMagenta,
    #  #'scaleFactor': 1e-2,
    #},
    #{
    #  'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/piAbsSelector/lariat_PiAbsAndChEx_flat_gam_v3/anahist.root",
    #  'addFriend': ["friend", "friendTree_gam_v3.root"],
    #  #'fn': "/lariat/app/users/jhugon/lariatsoft_v06_15_00/srcs/lariatsoft/JobConfigurations/gam_piAbsSelector.root",
    #  'name': "gam",
    #  'title': "#gamma MC",
    #  'caption': "#gamma MC",
    #  'color': root.kOrange-3,
    #  #'scaleFactor': 1e-2,
    #},
  ]

  histConfigs = [
    {
      'name': "xWC4Hit",
      'xtitle': "X Position at WC4 [cm]",
      'ytitle': "Normalized Events / bin",
      'binning': [100,0,50],
      'var': "xWC4Hit",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "yWC4Hit",
      'xtitle': "Y Position at WC4 [cm]",
      'ytitle': "Normalized Events / bin",
      'binning': [100,-25,25],
      'var': "yWC4Hit",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "zWC4Hit",
      'xtitle': "Z Position at WC4 [cm]",
      'ytitle': "Normalized Events / bin",
      'binning': [100,-100,-90],
      'var': "zWC4Hit",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "xWC",
      'xtitle': "X Position of WC track projection to TPC [cm]",
      'ytitle': "Normalized Events / bin",
      'binning': [100,0,75],
      'var': "xWC",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "yWC",
      'xtitle': "Y Position of WC track projection to TPC [cm]",
      'ytitle': "Normalized Events / bin",
      'binning': [100,-50,50],
      'var': "yWC",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "pzWC",
      'xtitle': "Z Momentum from WC [MeV/c]",
      'ytitle': "Normalized Events / bin",
      'binning': [100,0,2000],
      'var': "pzWC",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
      'printIntegral': True,
    },
    #{
    #  'name': "pWC",
    #  'xtitle': "Momentum from WC [MeV/c]",
    #  'ytitle': "Normalized Events / bin",
    #  'binning': [100,0,2000],
    #  'var': "pzWC",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "kinWC",
    #  'xtitle': "Kinetic Energy at WC [MeV/c] (m=m_{#pi^{#pm}})",
    #  'ytitle': "Normalized Events / bin",
    #  'binning': [100,0,2000],
    #  'var': "kinWC",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "kinWCInTPC",
      'xtitle': "Kinetic Energy at TPC [MeV/c] (m=m_{#pi^{#pm}})",
      'ytitle': "Normalized Events / bin",
      'binning': [100,0,2000],
      'var': "kinWCInTPC",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    #{
    #  'name': "phiWC",
    #  'xtitle': "WC track #phi [deg]",
    #  'ytitle': "Normalized Events / bin",
    #  'binning': [360,-180,180],
    #  'var': "phiWC*180/pi",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "thetaWC",
    #  'xtitle': "WC track #theta [deg]",
    #  'ytitle': "Normalized Events / bin",
    #  'binning': [40,0,10],
    #  'var': "thetaWC*180/pi",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "thetaxzWC",
      'xtitle': "WC track #theta_{xz} [deg]",
      'ytitle': "Normalized Events / bin",
      'binning': [100,-10,10],
      'var': "(atan(tan(thetaWC)*cos(phiWC)))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "thetayzWC",
      'xtitle': "WC track #theta_{yz} [deg]",
      'ytitle': "Normalized Events / bin",
      'binning': [100,-5,5],
      'var': "(asin(sin(thetaWC)*sin(phiWC)))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "sinthetayz",
      'xtitle': "WC Track sin(#theta_{yz})",
      'ytitle': "Tracks / bin",
      'binning': [80,-0.1,0.1],
      'var': "sin(thetaWC)*sin(phiWC)",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "nTracks",
      'xtitle': "Number of TPC Tracks / Event",
      'ytitle': "Events / bin",
      'binning': [31,0,30],
      'var': "nTracks",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "nTracksInFirstZ2",
      'xtitle': "Number of TPC Tracks in first 2 cm / Event",
      'ytitle': "Events / bin",
      'binning': [16,0,15],
      'var': "nTracksInFirstZ[2]",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "nTracksInFirstZ14",
      'xtitle': "Number of TPC Tracks in first 14 cm / Event",
      'ytitle': "Events / bin",
      'binning': [16,0,15],
      'var': "nTracksInFirstZ[14]",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "nTracksLengthLt5",
      'xtitle': "Number of TPC Tracks with length < 5 cm / Event",
      'ytitle': "Events / bin",
      'binning': [16,0,15],
      'var': "nTracksLengthLt[5]",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackMatchDeltaX",
      'xtitle': "TPC / WC Track #Delta x at TPC Front [cm]",
      'ytitle': "TPC Tracks / bin",
      'binning': [40,-20,20],
      'var': "trackMatchDeltaX",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackMatchDeltaY",
      'xtitle': "TPC / WC Track #Delta y at TPC Front [cm]",
      'ytitle': "TPC Tracks / bin",
      'binning': [40,-20,20],
      'var': "trackMatchDeltaY",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackMatchDeltaR",
      'xtitle': "TPC / WC Track #Delta r at TPC Front [cm]",
      'ytitle': "TPC Tracks / bin",
      'binning': [40,0,20],
      'var': "trackMatchDeltaR",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackMatchDeltaAngle",
      'xtitle': "TPC / WC Track #Delta #alpha at TPC Front [deg]",
      'ytitle': "TPC Tracks / bin",
      'binning': [90,0,180],
      'var': "trackMatchDeltaAngle*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "nTOFs",
      'xtitle': "Number of TOF Objects",
      'ytitle': "Events / bin",
      'binning': [11,0,10],
      'var': "nTOFs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "TOFs",
      'xtitle': "TOF [ns]",
      'ytitle': "Events / bin",
      'binning': [100,0,100],
      'var': "TOFs[0]",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackStartX",
      'xtitle': "TPC Track Start X [cm]",
      'ytitle': "Tracks / bin",
      'binning': [100,-20,60],
      'var': "trackStartX",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackStartY",
      'xtitle': "TPC Track Start Y [cm]",
      'ytitle': "Tracks / bin",
      'binning': [100,-50,50],
      'var': "trackStartY",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackStartZ",
      'xtitle': "TPC Track Start Z [cm]",
      'ytitle': "Tracks / bin",
      'binning': [100,-20,110],
      'var': "trackStartZ",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    #{
    #  'name': "trackEndX",
    #  'xtitle': "TPC Track End X [cm]",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,-20,60],
    #  'var': "trackEndX",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trackEndY",
    #  'xtitle': "TPC Track End Y [cm]",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,-50,50],
    #  'var': "trackEndY",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trackEndZ",
    #  'xtitle': "TPC Track End Z [cm]",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,-20,110],
    #  'var': "trackEndZ",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trackLength",
    #  'xtitle': "TPC Track Length [cm]",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,-10,100],
    #  'var': "trackLength",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
  ]

  for i in reversed(range(len(histConfigs))):
    if histConfigs[i]['name'] != "pzWC":
      histConfigs.pop(i)

  plotManyFilesOnePlot(fileConfigs,histConfigs,c,"PiAbsSelector/tree",nMax=NMAX)

  for i in range(len(histConfigs)):
    histConfigs[i]['cuts'] = weightStr + "*(pzWC > 450 && pzWC < 1100 && nTracksInFirstZ[2] >= 1 && nTracksInFirstZ[14] < 4 && nTracksLengthLt[5] < 3) && (isMC || (firstTOF > 28 && firstTOF < 55))"
    #histConfigs[i]['cuts'] = weightStr + "*(pzWC > 450 && pzWC < 1100 && nTracksInFirstZ[2] >= 1 && nTracksInFirstZ[14] < 4 && nTracksLengthLt[5] < 3) && (isMC || (firstTOF < 25))"
  plotManyFilesOnePlot(fileConfigs,histConfigs,c,"PiAbsSelector/tree",nMax=NMAX,outSuffix="HistCuts")

  for i in range(len(histConfigs)):
    histConfigs[i]['cuts'] = " allWeight *( pzWC > 450 && pzWC < 1100 && nTracksInFirstZ[2] >= 1 && nTracksInFirstZ[14] < 4 && nTracksLengthLt[5] < 3 && (isMC || (firstTOF > 28 && firstTOF < 55)))"
    #histConfigs[i]['cuts'] = " allWeight *( pzWC > 450 && pzWC < 1100 && nTracksInFirstZ[2] >= 1 && nTracksInFirstZ[14] < 4 && nTracksLengthLt[5] < 3 && (isMC || (firstTOF < 25)))"
  plotManyFilesOnePlot(fileConfigs,histConfigs,c,"PiAbsSelector/tree",nMax=NMAX,outSuffix="HistAllWeightsCuts")

  histConfigs = [
    {
      'name': "thetayzWCVthetaxzWC",
      'xtitle': "WC track #theta_{xz} [deg]",
      'ytitle': "WC track #theta_{yz} [deg]",
      'binning': [40,-10,10,40,-10,10],
      'var': "(asin(sin(thetaWC)*sin(phiWC)))*180/pi:(atan(tan(thetaWC)*cos(phiWC)))*180/pi",
      'cuts': "",
      #'normalize': True,
      #'logy': logy,
    },
    {
      'name': "xWCVthetaxzWC",
      'xtitle': "WC track #theta_{xz} [deg]",
      'ytitle': "X of WC track projected to front of TPC [cm]",
      'binning': [40,-10,10,40,0,75],
      'var': "xWC:(atan(tan(thetaWC)*cos(phiWC)))*180/pi",
      'cuts': "",
      #'normalize': True,
      #'logy': logy,
    },
    {
      'name': "xWCVxWC4Hit",
      'xtitle': "X of WC4 Hit [cm]",
      'ytitle': "X of WC track projected to front of TPC [cm]",
      'binning': [50,0,50,40,0,75],
      'var': "xWC:xWC4Hit",
      'cuts': "",
      #'normalize': True,
      #'logy': logy,
    },
  ]

  #plotOneHistOnePlot(fileConfigs,histConfigs,c,"PiAbsSelector/tree",nMax=NMAX)
