#!/usr/bin/env python

import ROOT as root
from helpers import *
root.gROOT.SetBatch(True)

if __name__ == "__main__":

  cuts = ""
  #cuts += "*(isMC || ((triggerBits >> 4) & 1))" # BEAMON trigger
  #cuts += "*(isMC || ((triggerBits >> 10) & 1))" # COSMICON trigger
  #cuts += "*(isMC || !((triggerBits >> 10) & 1))" # Not COSMICON trigger
  #cuts += "*(isMC || ((triggerBits >> 11) & 1))" # COSMIC trigger
  #cuts += "*(isMC || (nWCTracks ==0 && nTOFs ==0))"
  cuts += "*(iBestMatch >= 0)" # primary Track found
  #cuts += "*(acos(sin(primTrkStartTheta)*sin(primTrkStartPhi))*180./pi < 5. || acos(sin(primTrkStartTheta)*sin(primTrkStartPhi))*180./pi > 175.)" # theta vertical
  #cuts += "*((!isMC) || (trueStartMom>3000. && trueStartMom < 8000.))"
  #cuts += "*(primTrkResRanges[0] > 1.)"
  #cuts += "*(Iteration$ < 10)"
  cuts += "*(primTrkXs > 10. && primTrkXs < 38. && primTrkYs > -10. && primTrkYs < 10. && primTrkZs > 10. && primTrkZs < 80.)"
  cuts += "*(sqrt(pow(primTrkXs - trueStartX,2)+pow(primTrkYs - trueStartY,2)+pow(primTrkZs - trueStartZ,2)) < 3.)"

  #cuts += "*(trueStartTheta*180/pi < 90.)"

  weightStr = "1"+cuts
  nData = 30860.0
  logy = True

  c = root.TCanvas()
  NMAX=1000000000
  #NMAX=100
  fileConfigs = [
    {
      #'fn': "/pnfs/lariat/scratch/users/jhugon/v06_15_00/cosmicAna/lariat_PiAbsAndChEx_flat_isoInTPC_mup_test_v1/anahist.root",
      'fn': "lariat_PiAbsAndChEx_flat_isoInTPC_mup_test_v1_cosmicAna.root",
      'name': "UniformIsoMuon",
      'title': "#mu^{+} MC",
      'caption': "Uniform,Isotropic #mu^{+} MC",
      'isData': False,
    },
  ]

  histConfigs = [
#    {
#      'name': "trueStartMom",
#      'xtitle': "True Start Momentum [MeV/c]",
#      'ytitle': "Events / bin",
#      'binning': [150,0,1500],
#      'var': "trueStartMom",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trueLength",
#      'xtitle': "True Trajectory Length [cm]",
#      'ytitle': "Events / bin",
#      'binning': [150,0,1500],
#      'var': "sqrt(pow(trueEndX-trueStartX,2)+pow(trueEndY-trueStartY,2)+pow(trueEndZ-trueStartZ,2))",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackXFront",
#      'xtitle': "X of TPC Track Projection to TPC Front [cm]",
#      'ytitle': "TPC Tracks / bin",
#      'binning': [50,0,50],
#      'var': "trackXFront",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackYFront",
#      'xtitle': "Y of TPC Track Projection to TPC Front [cm]",
#      'ytitle': "TPC Tracks / bin",
#      'binning': [50,-50,50],
#      'var': "trackYFront",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackMatchLowestZ",
#      'xtitle': "TPC Track Start Z [cm]",
#      'ytitle': "TPC Tracks / bin",
#      'binning': [40,0,20],
#      'var': "trackMatchLowestZ",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "nTOFs",
#      'xtitle': "Number of TOF Objects",
#      'ytitle': "Events / bin",
#      'binning': [11,0,10],
#      'var': "nTOFs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackStartX",
#      'xtitle': "TPC Track Start X [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-20,60],
#      'var': "trackStartX",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackStartY",
#      'xtitle': "TPC Track Start Y [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-50,50],
#      'var': "trackStartY",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackStartZ",
#      'xtitle': "TPC Track Start Z [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-20,110],
#      'var': "trackStartZ",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackEndX",
#      'xtitle': "TPC Track End X [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-20,60],
#      'var': "trackEndX",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackEndY",
#      'xtitle': "TPC Track End Y [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-50,50],
#      'var': "trackEndY",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackEndZ",
#      'xtitle': "TPC Track End Z [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-20,110],
#      'var': "trackEndZ",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "trackLength",
#      'xtitle': "TPC Track Length [cm]",
#      'ytitle': "Tracks / bin",
#      'binning': [100,-10,100],
#      'var': "trackLength",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
    #{
    #  'name': "trackCaloKin",
    #  'xtitle': "TPC Calo Estimate of KE [MeV]",
    #  'ytitle': "Tracks / bin",
    #  'binning': [50,0,2500],
    #  'var': "trackCaloKin",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "primTrkLength",
      'xtitle': "Primary TPC Track Length [cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,100],
      'var': "primTrkLength",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
      'printIntegral': True,
    },
    {
      'name': "primTrkStartTheta",
      'xtitle': "Primary TPC Track #theta [deg]",
      'ytitle': "Events / bin",
      'binning': [180,0,180],
      'var': "primTrkStartTheta*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartCosTheta",
      'xtitle': "Primary TPC Track cos(#theta)",
      'ytitle': "Events / bin",
      'binning': [100,0,1],
      'var': "cos(primTrkStartTheta)",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartPhi",
      'xtitle': "Primary TPC Track #phi [deg]",
      'ytitle': "Events / bin",
      'binning': [180,-180,180],
      'var': "primTrkStartPhi*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartThetaY",
      'xtitle': "Primary TPC Track #theta_{y} [deg]",
      'ytitle': "Events / bin",
      'binning': [180,0,180],
      'var': "acos(sin(primTrkStartTheta)*sin(primTrkStartPhi))*180./pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartCosThetaY",
      'xtitle': "Primary TPC Track cos(#theta_{y})",
      'ytitle': "Events / bin",
      'binning': [100,0,1],
      'var': "sin(primTrkStartTheta)*sin(primTrkStartPhi)",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartPhiZX",
      'xtitle': "Primary TPC Track #phi_{zx} [deg]",
      'ytitle': "Events / bin",
      'binning': [180,-180,180],
      'var': "atan2(sin(primTrkStartTheta)*cos(primTrkStartPhi),cos(primTrkStartTheta))*180./pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartThetaX",
      'xtitle': "Primary TPC Track #theta_{x} [deg]",
      'ytitle': "Events / bin",
      'binning': [180,0,180],
      'var': "acos(sin(primTrkStartTheta)*cos(primTrkStartPhi))*180./pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartCosThetaX",
      'xtitle': "Primary TPC Track cos(#theta_{x})",
      'ytitle': "Events / bin",
      'binning': [100,0,1],
      'var': "sin(primTrkStartTheta)*cos(primTrkStartPhi)",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkStartPhiZY",
      'xtitle': "Primary TPC Track #phi_{zy} [deg]",
      'ytitle': "Events / bin",
      'binning': [180,-180,180],
      'var': "atan2(sin(primTrkStartTheta)*sin(primTrkStartPhi),cos(primTrkStartTheta))*180./pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs_zoom",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,10],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      'normalize': not logy,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs_zoom2",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,10],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      'normalize': logy,
      'logy': not logy,
    },
    {
      'name': "primTrkdEdxs_zoom3",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [50,0,5],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      'normalize': logy,
      'logy': not logy,
    },
    {
      'name': "primTrkTruedEdxs",
      'xtitle': "Primary TPC Track True dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,50],
      'var': "primTrkTruedEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkTruedEdxs_zoom",
      'xtitle': "Primary TPC Track True dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,10],
      'var': "primTrkTruedEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
#    {
#      'name': "primTrkdQdxs",
#      'xtitle': "Primary TPC Track dQ/dx [ADC/cm]",
#      'ytitle': "Events / bin",
#      'binning': [300,0,3e4],
#      'var': "primTrkdQdxs*((0.5-1.)*isMC + 1.)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "primTrkdQdxs_zoom",
#      'xtitle': "Primary TPC Track dQ/dx [ADC/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,8e3],
#      'var': "primTrkdQdxs*((0.5-1.)*isMC + 1.)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#      'printIntegral' : True,
#    },
#    {
#      'name': "primTrkdQdxs_zoom2",
#      'xtitle': "Primary TPC Track dQ/dx [ADC/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,8e3],
#      'var': "primTrkdQdxs*((0.5-1.)*isMC + 1.)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': not logy,
#      'printIntegral' : True,
#    },
#    {
#      'name': "primTrkdQs",
#      'xtitle': "Primary TPC Track dQ [ADC]",
#      'ytitle': "Events / bin",
#      'binning': [200,0,8e3],
#      'var': "primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': not logy,
#      'printIntegral' : True,
#    },
#    {
#      'name': "primTrkTruedQdxs",
#      'xtitle': "Primary TPC Track True dQ/dx [e^{-}/cm]",
#      'ytitle': "Events / bin",
#      'binning': [200,0,5e6],
#      'var': "primTrkTruedQdxs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "primTrkTruedQdxs_zoom",
#      'xtitle': "Primary TPC Track True dQ/dx [e^{-}/cm]",
#      'ytitle': "Events / bin",
#      'binning': [200,0,1e5],
#      'var': "primTrkTruedQdxs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "primTrkTruedQs",
#      'xtitle': "Primary TPC Track Q [e^{-}]",
#      'ytitle': "Events / bin",
#      #'binning': [200,0,1e5],
#      'binning': getLogBins(100,1e3,1e7),
#      'var': "primTrkTruedQs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#      'logx': True,
#    },
#    {
#      'name': "primTrkTruedQs2",
#      'xtitle': "Primary TPC Track Q [e^{-}]",
#      'ytitle': "Events / bin",
#      'binning': [200,0,2e5],
#      'var': "primTrkTruedQs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': not logy,
#      'logx': False,
#    },
#    {
#      'name': "primTrkdEdxs_Q1000to1500_zoom2",
#      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,10],
#      'var': "primTrkdEdxs",
#      'cuts': weightStr+"*(primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) > 1000. && primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) < 1500.)",
#      #'normalize': True,
#      'logy': not logy,
#      'caption': "1000 ADC < Q < 1500 ADC",
#    },
#    {
#      'name': "primTrkdEdxs_Q1500to2000_zoom2",
#      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,10],
#      'var': "primTrkdEdxs",
#      'cuts': weightStr+"*(primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) > 1500. && primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) < 2000.)",
#      #'normalize': True,
#      'logy': not logy,
#      'caption': "1500 ADC < Q < 2000 ADC",
#    },
#    {
#      'name': "primTrkdEdxs_Q2000to3000_zoom2",
#      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,10],
#      'var': "primTrkdEdxs",
#      'cuts': weightStr+"*(primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) > 2000. && primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) < 3000.)",
#      #'normalize': True,
#      'logy': not logy,
#      'caption': "2000 ADC < Q < 3000 ADC",
#    },
#    {
#      'name': "primTrkdEdxs_Q3000to4000_zoom2",
#      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,10],
#      'var': "primTrkdEdxs",
#      'cuts': weightStr+"*(primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) > 3000. && primTrkdQdxs*primTrkPitches*((0.5-1.)*isMC + 1.) < 4000.)",
#      #'normalize': True,
#      'logy': not logy,
#      'caption': "3000 ADC < Q < 4000 ADC",
#    },
    #{
    #  'name': "primTrkdEdxsFidCut",
    #  'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
    #  'ytitle': "Events / bin",
    #  'binning': [200,0,50],
    #  'var': "primTrkdEdxs",
    #  'cuts': weightStr+"*primTrkInFids",
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "primTrkResRanges",
      'xtitle': "Primary TPC Track Residual Range [cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,100],
      'var': "primTrkResRanges",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkPitches",
      'xtitle': "Primary TPC Track Pitch [cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,10],
      'var': "primTrkPitches",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    #{
    #  'name': "primTrkEndKin",
    #  'xtitle': "Primary TPC Track End Kinetic Energy [MeV]",
    #  'ytitle': "Events / bin",
    #  'binning': [50,0,1000],
    #  'var': "primTrkEndKin",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "primTrkEndKinFid",
    #  'xtitle': "Primary TPC Track End Kinetic Energy [MeV]",
    #  'ytitle': "Events / bin",
    #  'binning': [50,0,1000],
    #  'var': "primTrkEndKinFid",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trueEndProcess",
    #  'xtitle': "trueEndProcess",
    #  'ytitle': "Events / bin",
    #  'binning': [17,0,17],
    #  'var': "trueEndProcess",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "trueStartTheta",
      'xtitle': "True Start #theta [deg]",
      'binning': [90,0,180],
      'var': "trueStartTheta*180/pi",
      'cuts': weightStr,
      #'normalize': True,
    },
    {
      'name': "trueStartCosTheta",
      'xtitle': "True Start cos(#theta)",
      'binning': [100,0,1],
      'var': "cos(trueStartTheta)",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trueStartPhi",
      'xtitle': "True Start #phi",
      'binning': [90,-180,180],
      'var': "trueStartPhi*180/pi",
      'cuts': weightStr,
      #'normalize': True,
    },
    {
      'name': "trueStartThetaY",
      'xtitle': "True Start #theta_{y} [deg]",
      'ytitle': "Events / bin",
      'binning': [180,0,180],
      'var': "acos(sin(trueStartTheta)*sin(trueStartPhi))*180./pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trueStartCosThetaY",
      'xtitle': "True Start cos(#theta_{y})",
      'ytitle': "Events / bin",
      'binning': [100,0,1],
      'var': "sin(trueStartTheta)*sin(trueStartPhi)",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trueStartPhiZX",
      'xtitle': "True Start #phi_{zx} [deg]",
      'ytitle': "Events / bin",
      'binning': [180,-180,180],
      'var': "atan2(sin(trueStartTheta)*cos(trueStartPhi),cos(trueStartTheta))*180./pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trueStartThetaX",
      'xtitle': "True Start #theta_{x} [deg]",
      'ytitle': "Events / bin",
      'binning': [180,0,180],
      'var': "acos(sin(trueStartTheta)*cos(trueStartPhi))*180./pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trueStartCosThetaX",
      'xtitle': "True Start cos(#theta_{x})",
      'ytitle': "Events / bin",
      'binning': [100,0,1],
      'var': "sin(trueStartTheta)*cos(trueStartPhi)",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trueStartPhiZY",
      'xtitle': "True Start #phi_{zy} [deg]",
      'ytitle': "Events / bin",
      'binning': [180,-180,180],
      'var': "atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180./pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trueCosThetaPitch",
      'xtitle': "True Start cos(#theta_{pitch})",
      'ytitle': "Events / bin",
      'binning': [50,0,1],
      'var': "fabs(cos(trueStartTheta)*cos(trueStartPhi)+sin(trueStartTheta)*cos(trueStartPhi))",
      'cuts': weightStr,
      #'normalize': True,
      'logy': False,
    },
    {
      'name': "recoCosThetaPitch",
      'xtitle': "Reconstructed cos(#theta_{pitch})",
      'ytitle': "Events / bin",
      'binning': [50,0,1],
      'var': "0.4/primTrkPitches",
      'cuts': weightStr,
      #'normalize': True,
      'logy': False,
    },
  ]

  plotOneHistOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="UnifIso_")
#  fileConfigMCs = copy.deepcopy(fileConfigs)
#  fileConfigData = None
#  for i in reversed(range(len(fileConfigMCs))):
#    if 'isData' in fileConfigMCs[i] and fileConfigMCs[i]['isData']:
#      fileConfigData = fileConfigMCs.pop(i)
#  DataMCStack(fileConfigData,fileConfigMCs,histConfigs,c,"PiAbsSelector/tree",nMax=NMAX)

########################################################
########################################################
########################################################

  histConfigs = [
    {
      'name': "primTrkdEdxs",
      'title': "All",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      'color': root.kBlack,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs",
      'title': "x < 10 cm",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr + "*(primTrkXs < 10.)",
      'color': root.kBlue-7,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs",
      'title': "10 cm < x < 20 cm",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr + "*(primTrkXs > 10. && primTrkXs < 20.)",
      'color': root.kRed-4,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs",
      'title': "20 cm < x < 30 cm",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr + "*(primTrkXs > 20. && primTrkXs < 30.)",
      'color': root.kGreen,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs",
      'title': "30 cm < x < 40 cm",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr + "*(primTrkXs > 30. && primTrkXs < 40.)",
      'color': root.kMagenta-4,
      #'normalize': True,
      'logy': logy,
    },
  ]

#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="Cosmics_dEdxForX")

########################################################
########################################################
########################################################

  histConfigs = [
#    {
#      'name': "primTrkdEdxVRange",
#      'xtitle': "Primary Track Hit Residual Range [cm]",
#      'ytitle': "Primary Track Hit dE/dx [MeV/cm]",
#      'binning': [100,0,100,100,0,50],
#      'var': "primTrkdEdxs:primTrkResRanges",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "primTrkdEdxVRangeFidCut",
#      'xtitle': "Primary Track Hit Residual Range [cm]",
#      'ytitle': "Primary Track Hit dE/dx [MeV/cm]",
#      'binning': [100,0,100,100,0,50],
#      'var': "primTrkdEdxs:primTrkResRanges",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "trackYFrontVtrackXFront",
#      'xtitle': "X of TPC Track Projection to TPC Front [cm]",
#      'ytitle': "Y of TPC Track Projection to TPC Front [cm]",
#      'binning': [40,0,40,40,-20,20],
#      'var': "trackYFront:trackXFront",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "primTrkdEdxVwire",
#      'xtitle': "Primary Track Hit Wire Number",
#      'ytitle': "Primary Track Hit dE/dx [MeV/cm]",
#      'binning': [240,0,240,100,0,10],
#      'var': "primTrkdEdxs:primTrkTrueWires",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "primTrkStartThetaVPhi",
#      'xtitle': "Primary TPC Track #phi [deg]",
#      'ytitle': "Primary TPC Track #theta [deg]",
#      'binning': [90,-180,180,90,0,180],
#      'var': "primTrkStartTheta*180/pi:primTrkStartPhi*180/pi",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "primTrkStartThetaYVprimTrkStartPhiZX",
#      'xtitle': "Primary TPC Track #phi_{zx} [deg]",
#      'ytitle': "Primary TPC Track #theta_{y} [deg]",
#      'binning': [90,-180,180,90,0,180],
#      'var': "acos(sin(primTrkStartTheta)*sin(primTrkStartPhi))*180/pi:atan2(sin(primTrkStartTheta)*cos(primTrkStartPhi),cos(primTrkStartTheta))*180/pi",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': False,
#    },
#    {
#      'name': "primTrkStartThetaXVprimTrkStartPhiZY",
#      'xtitle': "Primary TPC Track #phi_{zy} [deg]",
#      'ytitle': "Primary TPC Track #theta_{x} [deg]",
#      'binning': [90,-180,180,90,0,180],
#      'var': "acos(sin(primTrkStartTheta)*cos(primTrkStartPhi))*180/pi:atan2(sin(primTrkStartTheta)*sin(primTrkStartPhi),cos(primTrkStartTheta))*180/pi",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': False,
#    },
    {
      'name': "primTrkdEdxsVx",
      'xtitle': "Hit x [cm]",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [60,-5,55,100,0,5],
      'var': "primTrkdEdxs:primTrkXs",
      'cuts': weightStr,
      #'normalize': True,
      'logz': True,
    },
    {
      'name': "primTrkdEdxsVy",
      'xtitle': "Hit y [cm]",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [50,-25,25,100,0,5],
      'var': "primTrkdEdxs:primTrkYs",
      'cuts': weightStr,
      #'normalize': True,
      'logz': True,
    },
    {
      'name': "primTrkdEdxsVz",
      'xtitle': "Hit z [cm]",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [100,-5,95,100,0,5],
      'var': "primTrkdEdxs:primTrkZs",
      'cuts': weightStr,
      #'normalize': True,
      'logz': True,
    },
    {
      'name': "primTrkdEdxsVprimTrkPitches",
      'xtitle': "Hit Pitch [cm]",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      #'binning': [30,0,6,10000,0,50],
      'binning': [[0.4,0.6,1.,2.,5,20],getLinBins(10000,0,50)],
      'var': "primTrkdEdxs:primTrkPitches",
      'cuts': weightStr,
      #'normalize': True,
      'logz': True,
    },
#    {
#      'name': "primTrkdEdxsV1OprimTrkPitches",
#      'xtitle': "(Hit Pitch)^{-1} [cm^{-1}]",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [50,0,5,10000,0,50],
#      'var': "primTrkdEdxs:1./primTrkPitches",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
#    {
#      'name': "primTrkdEdxsVrun",
#      'xtitle': "Run Number",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [200,8000,1000,500,0,50],
#      'var': "primTrkdEdxs:runNumber",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
#    {
#      'name': "primTrkdEdxsVyFromCenter",
#      'xtitle': "Hit |y| [cm]",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [40,0,25,10000,0,50],
#      'var': "primTrkdEdxs:fabs(primTrkYs)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
#    {
#      'name': "primTrkdEdxsVzFromCenter",
#      'xtitle': "Hit |z-45| [cm]",
#      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
#      'binning': [40,0,50,10000,0,50],
#      'var': "primTrkdEdxs:fabs(primTrkZs-45.)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logz': True,
#    },
    {
      'name': "primTrkdEdxsVtrueStartTheta",
      'xtitle': "True Start #theta [deg]",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [30,0,180,100,0,5],
      'var': "primTrkdEdxs:trueStartTheta*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
    {
      'name': "primTrkdEdxsVtrueStartCosTheta",
      'xtitle': "True Start cos(#theta)",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [50,0,1,100,0,5],
      'var': "primTrkdEdxs:cos(trueStartTheta)",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
    {
      'name': "primTrkdEdxsVtrueStartPhi",
      'xtitle': "True Start #phi",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [30,-180,180,100,0,5],
      'var': "primTrkdEdxs:trueStartPhi*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
    {
      'name': "primTrkdEdxsVtrueStartThetaX",
      'xtitle': "True Start #theta_{x} [deg]",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [60,0,180,100,0,5],
      'var': "primTrkdEdxs:acos(sin(trueStartTheta)*cos(trueStartPhi))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkdEdxsVtrueStartCosThetaX",
      'xtitle': "True Start cos(#theta_{x})",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [50,0,1,100,0,5],
      'var': "primTrkdEdxs:sin(trueStartTheta)*cos(trueStartPhi)",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkdEdxsVtrueStartThetaX_zoom",
      'xtitle': "True Start #theta_{x} [deg]",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [60,0,180,100,0,5],
      'var': "primTrkdEdxs:acos(sin(trueStartTheta)*cos(trueStartPhi))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkdEdxsVtrueStartCosThetaX_zoom",
      'xtitle': "True Start cos(#theta_{x})",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [50,0,1,100,0,5],
      'var': "primTrkdEdxs:sin(trueStartTheta)*cos(trueStartPhi)",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkdEdxsVtrueStartPhiZY",
      'xtitle': "True Start #phi_{zy}",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [60,-180,180,10000,0,50],
      'var': "primTrkdEdxs:atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkdEdxsVtrueStartPhiZY_zoom",
      'xtitle': "True Start #phi_{zy}",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [60,-180,180,100,0,5],
      'var': "primTrkdEdxs:atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkdEdxsVtrueStartPhiZY_zoom_onlyCentral",
      'xtitle': "True Start #phi_{zy}",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [60,-180,180,100,0,5],
      'var': "primTrkdEdxs:atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': "(iBestMatch >= 0)"+"*(primTrkXs > 10. && primTrkXs < 38. && primTrkYs > -10. && primTrkYs < 10. && primTrkZs > 10. && primTrkZs < 80.)",
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkdEdxsVtrueStartPhiZY_zoom_onlyNearVertex",
      'xtitle': "True Start #phi_{zy}",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [60,-180,180,100,0,5],
      'var': "primTrkdEdxs:atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': "(iBestMatch >= 0)"+"*(sqrt(pow(primTrkXs - trueStartX,2)+pow(primTrkYs - trueStartY,2)+pow(primTrkZs - trueStartZ,2))<3.)",
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkdEdxsVtrueStartPhiZY_zoom_noCuts",
      'xtitle': "True Start #phi_{zy}",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [60,-180,180,100,0,5],
      'var': "primTrkdEdxs:atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': "(iBestMatch >= 0)",
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkdEdxsVtrueStartPhiZY_zoom_logy",
      'xtitle': "True Start #phi_{zy}",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [60,-180,180,100,0,5],
      'var': "primTrkdEdxs:atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': True,
    },
    {
      'name': "primTrkdEdxsVtrueStartThetaY",
      'xtitle': "True Start #theta_{y} [deg]",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [30,0,180,100,0,5],
      'var': "primTrkdEdxs:acos(sin(trueStartTheta)*sin(trueStartPhi))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
    {
      'name': "primTrkdEdxsVtrueStartCosThetaY",
      'xtitle': "True Start cos(#theta_{y})",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [50,0,1,100,0,5],
      'var': "primTrkdEdxs:sin(trueStartTheta)*sin(trueStartPhi)",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
    {
      'name': "primTrkdEdxsVtrueStartPhiZX",
      'xtitle': "True Start #phi_{zx}",
      'ytitle': "Primary TPC Track dE/dx [MeV/cm]",
      'binning': [30,-180,180,100,0,5],
      'var': "primTrkdEdxs:atan2(sin(trueStartTheta)*cos(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
    {
      'name': "trueStartThetaVtrueStartPhi",
      'xtitle': "True Start #phi [deg]",
      'ytitle': "True Start #theta [deg]",
      'binning': [90,-180,180,90,0,180],
      'var': "trueStartTheta*180/pi:trueStartPhi*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': False,
    },
    {
      'name': "trueStartCosThetaVtrueStartPhi",
      'xtitle': "True Start #phi [deg]",
      'ytitle': "True Start cos(#theta)",
      'binning': [90,-180,180,100,0,1],
      'var': "cos(trueStartTheta):trueStartPhi*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': False,
    },
    {
      'name': "trueStartThetaYVtrueStartPhiZX",
      'xtitle': "True Start #phi_{zx} [deg]",
      'ytitle': "True Start #theta_{y} [deg]",
      'binning': [90,-180,180,90,0,180],
      'var': "acos(sin(trueStartTheta)*sin(trueStartPhi))*180/pi:atan2(sin(trueStartTheta)*cos(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': False,
    },
    {
      'name': "trueStartCosThetaYVtrueStartPhiZX",
      'xtitle': "True Start #phi_{zx} [deg]",
      'ytitle': "True Start cos(#theta_{y})",
      'binning': [90,-180,180,100,0,1],
      'var': "sin(trueStartTheta)*sin(trueStartPhi):atan2(sin(trueStartTheta)*cos(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': False,
    },
    {
      'name': "trueStartThetaXVtrueStartPhiZY",
      'xtitle': "True Start #phi_{zy} [deg]",
      'ytitle': "True Start #theta_{x} [deg]",
      'binning': [90,-180,180,90,0,180],
      'var': "acos(sin(trueStartTheta)*cos(trueStartPhi))*180/pi:atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "trueStartCosThetaXVtrueStartPhiZY",
      'xtitle': "True Start #phi_{zy} [deg]",
      'ytitle': "True Start cos(#theta_{x})",
      'binning': [90,-180,180,100,0,1],
      'var': "sin(trueStartTheta)*cos(trueStartPhi):atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
#    {
#      'name': "trueStartCosThetaXVtrueStartPhiZY_primTrkPitchesGt2",
#      'xtitle': "True Start #phi_{zy} [deg]",
#      'ytitle': "True Start cos(#theta_{x})",
#      'binning': [90,-180,180,100,0,1],
#      'var': "sin(trueStartTheta)*cos(trueStartPhi):atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
#      'cuts': weightStr+"*(primTrkPitches > 2.)",
#      #'normalize': True,
#      'logz': False,
#    },
#    {
#      'name': "trueStartCosThetaXVtrueStartPhiZY_primTrkPitchesGt5",
#      'xtitle': "True Start #phi_{zy} [deg]",
#      'ytitle': "True Start cos(#theta_{x})",
#      'binning': [90,-180,180,100,0,1],
#      'var': "sin(trueStartTheta)*cos(trueStartPhi):atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
#      'cuts': weightStr+"*(primTrkPitches > 5.)",
#      #'normalize': True,
#      'logz': False,
#    },
#    {
#      'name': "trueStartCosThetaXVtrueStartPhiZY_primTrkPitchesGt10",
#      'xtitle': "True Start #phi_{zy} [deg]",
#      'ytitle': "True Start cos(#theta_{x})",
#      'binning': [90,-180,180,100,0,1],
#      'var': "sin(trueStartTheta)*cos(trueStartPhi):atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
#      'cuts': weightStr+"*(primTrkPitches > 10.)",
#      #'normalize': True,
#      'logz': False,
#    },
#    {
#      'name': "hitYVhitX",
#      'xtitle': "Hit x [cm]",
#      'ytitle': "Hit y [cm]",
#      'binning': [60,-5,55,60,-30,30],
#      'var': "primTrkYs:primTrkXs",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitYVhitZ",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit y [cm]",
#      'binning': [120,-10,110,60,-30,30],
#      'var': "primTrkYs:primTrkZs",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitXVhitZ",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit x [cm]",
#      'binning': [120,-10,110,60,-5,55],
#      'var': "primTrkXs:primTrkZs",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitYVhitX_cosmicon",
#      'xtitle': "Hit x [cm]",
#      'ytitle': "Hit y [cm]",
#      'binning': [60,-5,55,60,-30,30],
#      'var': "primTrkYs:primTrkXs",
#      'cuts': "1"+"*(isMC || ((triggerBits >> 10) & 1))",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitYVhitZ_cosmicon",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit y [cm]",
#      'binning': [120,-10,110,60,-30,30],
#      'var': "primTrkYs:primTrkZs",
#      'cuts': "1"+"*(isMC || ((triggerBits >> 10) & 1))",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitXVhitZ_cosmicon",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit x [cm]",
#      'binning': [120,-10,110,60,-5,55],
#      'var': "primTrkXs:primTrkZs",
#      'cuts': "1"+"*(isMC || ((triggerBits >> 10) & 1))",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitXVhitZ_NotCosmicon",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit x [cm]",
#      'binning': [120,-10,110,60,-5,55],
#      'var': "primTrkXs:primTrkZs",
#      'cuts': "1"+"*(isMC || !((triggerBits >> 10) & 1))",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitYVhitZ_cosmic",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit y [cm]",
#      'binning': [120,-10,110,60,-30,30],
#      'var': "primTrkYs:primTrkZs",
#      'cuts': "1"+"*(isMC || ((triggerBits >> 11) & 1))",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitYVhitZ_beamon",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit y [cm]",
#      'binning': [120,-10,110,60,-30,30],
#      'var': "primTrkYs:primTrkZs",
#      'cuts': "1"+"*(isMC || ((triggerBits >> 4) & 1))",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "hitYVhitZ_pickytrack",
#      'xtitle': "Hit z [cm]",
#      'ytitle': "Hit y [cm]",
#      'binning': [120,-10,110,60,-30,30],
#      'var': "primTrkYs:primTrkZs",
#      'cuts': "1"+"*(isMC || nWCTracks > 0)",
#      #'normalize': True,
#      #'logz': True,
#    },
    {
      'name': "primTrkCosThetaPitchVtrueCosThetaPitch",
      'xtitle': "True |cos(#theta_{pitch})|",
      'ytitle': "Reconstruction |cos(#theta_{pitch})|",
      'binning': [30,0,1,30,0,1],
      #'var': "0.4/primTrkPitches:fabs(cos(trueStartTheta)*cos(pi/3.)+sin(trueStartTheta)*sin(pi/3.)*cos(trueStartPhi-0.5*pi))",
      #'var': "0.4/primTrkPitches:fabs(cos(trueStartTheta)*cos(pi/3.)+sin(trueStartTheta)*sin(pi/3.)*cos(trueStartPhi-0.5*pi))",
      'var': "0.4/primTrkPitches:fabs(cos(trueStartTheta)*cos(pi/3.)+sin(trueStartTheta)*sin(pi/3.)*cos(trueStartPhi-0.5*pi))",
      'cuts': "(iBestMatch >= 0)*(Iteration$ == 0)",
      #'normalize': True,
      'logy': False,
    },
    {
      'name': "primTrkCosThetaPitchVtrueCosThetaPitch_dottingThings",
      'xtitle': "True |cos(#theta_{pitch})|",
      'ytitle': "Reconstruction |cos(#theta_{pitch})|",
      'binning': [30,0,1,30,0,1],
      'var': "0.4/primTrkPitches:fabs(cos(trueStartTheta)*cos(pi/3.)+sin(trueStartTheta)*sin(pi/3.)*sin(trueStartPhi)*sin(0.5*pi))",
      'cuts': "(iBestMatch >= 0)*(Iteration$ == 0)",
      #'normalize': True,
      'logy': False,
    },
    {
      'name': "primTrkThetaPitchVtrueThetaPitch_dottingThings",
      'xtitle': "True #theta_{pitch}",
      'ytitle': "Reconstruction #theta_{pitch}",
      'binning': [30,0,90,30,0,90],
      'var': "acos(0.4/primTrkPitches)*180/pi:acos(fabs(cos(trueStartTheta)*cos(pi/3.)+sin(trueStartTheta)*sin(pi/3.)*sin(trueStartPhi)*sin(0.5*pi)))*180/pi",
      'cuts': "(iBestMatch >= 0)*(Iteration$ == 0)",
      #'normalize': True,
      'logy': False,
    },
    {
      'name': "primTrkCosThetaPitchVtrueCosThetaPitchZY",
      'xtitle': "True |cos(#theta_{z/y-plane pitch})|",
      'ytitle': "Reconstruction |cos(#theta_{pitch})|",
      'binning': [30,0,1,30,0,1],
      'var': "0.4/primTrkPitches:fabs(cos(atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))-pi/3.))",
      'cuts': "(iBestMatch >= 0)*(Iteration$ == 0)",
      #'normalize': True,
      'logy': False,
    },
    {
      'name': "primTrkThetaPitchVtrueThetaPitchZY",
      'xtitle': "True #theta_{z/y-plane pitch}",
      'ytitle': "Reconstruction #theta_{pitch}",
      'binning': [30,0,180,30,0,180],
      'var': "acos(0.4/primTrkPitches)*180/pi:fabs(atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))-pi/3.)*180/pi",
      'cuts': "(iBestMatch >= 0)*(Iteration$ == 0)",
      #'normalize': True,
      'logy': False,
    },
    {
      'name': "primTrkStartPhiVtrueStartPhi",
      'xtitle': "True Start #phi_{xy} [deg]",
      'ytitle': "TPC Track Start #phi_{xy} [deg]",
      'binning': [180,-180,180,180,-180,180],
      'var': "primTrkStartPhi*180/pi:trueStartPhi*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkStartThetaVtrueStartTheta",
      'xtitle': "True Start #theta_{z} [deg]",
      'ytitle': "TPC Track Start #theta_{z} [deg]",
      'binning': [180,0,180,180,0,180],
      'var': "primTrkStartTheta*180/pi:trueStartTheta*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkStartPhiZYVtrueStartPhiZY",
      'xtitle': "True Start #phi_{zy} [deg]",
      'ytitle': "TPC Track Start #phi_{zy} [deg]",
      'binning': [180,-180,180,180,-180,180],
      'var': "atan2(sin(primTrkStartTheta)*sin(primTrkStartPhi),cos(primTrkStartTheta))*180/pi:atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkStartThetaXVtrueStartThetaX",
      'xtitle': "True Start #theta_{x} [deg]",
      'ytitle': "TPC Track Start #theta_{x} [deg]",
      'binning': [180,0,180,180,0,180],
      'var': "acos(sin(primTrkStartTheta)*cos(primTrkStartPhi))*180/pi:acos(sin(trueStartTheta)*cos(trueStartPhi))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkStartTanPhiZYVtrueStartTanPhiZY",
      'xtitle': "True Start |tan(#phi_{zy})|",
      'ytitle': "TPC Track Start |tan(#phi_{zy})|",
      'binning': [100,0,20,100,0,20],
      'var': "fabs(tan(primTrkStartTheta)*sin(primTrkStartPhi)):fabs(tan(trueStartTheta)*sin(trueStartPhi))",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkStartCosPhiZYVtrueStartCosPhiZY",
      'xtitle': "True Start |cos(#phi_{zy})|",
      'ytitle': "TPC Track Start |cos(#phi_{zy})|",
      'binning': [100,0,1,100,0,1],
      'var': "fabs(cos(atan2(sin(primTrkStartTheta)*sin(primTrkStartPhi),cos(primTrkStartTheta)))):fabs(cos(atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))))",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkStartSinPhiZYVtrueStartSinPhiZY",
      'xtitle': "True Start |sin(#phi_{zy})|",
      'ytitle': "TPC Track Start |sin(#phi_{zy})|",
      'binning': [100,0,1,100,0,1],
      'var': "fabs(sin(atan2(sin(primTrkStartTheta)*sin(primTrkStartPhi),cos(primTrkStartTheta)))):fabs(sin(atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))))",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "primTrkStartCosThetaXVtrueStartCosThetaX",
      'xtitle': "True Start |cos(#theta_{x})|",
      'ytitle': "TPC Track Start |cos(#theta_{x})|",
      'binning': [100,0,1,100,0,1],
      'var': "sin(primTrkStartTheta)*cos(primTrkStartPhi):sin(trueStartTheta)*cos(trueStartPhi)",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "deltaRecoTruePhiZYVtrueStartPhiZY",
      'xtitle': "True Start #phi_{zy} [deg]",
      'ytitle': "Reco - True #Delta #phi_{zy} [deg]",
      'binning': [60,-180,180,90,-180,180],
      'var': "(atan2(sin(primTrkStartTheta)*sin(primTrkStartPhi),cos(primTrkStartTheta))-atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta)))*180/pi:atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "deltaRecoTrueThetaXVtrueStartCosThetaX",
      'xtitle': "True Start |cos(#theta_{x})|",
      'ytitle': "Reco - True #Delta #theta_{x} [deg]",
      'binning': [50,0,1,90,-180,180],
      'var': "(acos(sin(primTrkStartTheta)*cos(primTrkStartPhi))-acos(sin(trueStartTheta)*cos(trueStartPhi)))*180/pi:fabs(sin(trueStartTheta)*cos(trueStartPhi))",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "deltaRecoTrueThetaXVtrueStartPhiZY",
      'xtitle': "True Start #phi_{zy} [deg]",
      'ytitle': "Reco - True #Delta #theta_{x} [deg]",
      'binning': [60,0,180,90,-180,180],
      'var': "(acos(sin(primTrkStartTheta)*cos(primTrkStartPhi))-acos(sin(trueStartTheta)*cos(trueStartPhi)))*180/pi:atan2(sin(trueStartTheta)*sin(trueStartPhi),cos(trueStartTheta))*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
  ]

  hists = plotOneHistOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="UnifIso_")
  outfile = root.TFile("unifiso_hists.root","recreate")
  outfile.cd()
  for var in hists:
    for ds in hists[var]:
        newname = var+"_"+ds
        hist = hists[var][ds]
        hist.SetName(newname)
        hist.Print()
        hist.Write()
  outfile.Close()

######################################################################################
######################################################################################
######################################################################################
######################################################################################

  histConfigs = [
    {
      'name': "primTrkdEdxs",
      "title": "Reco",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [400,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkTruedEdxs",
      "title": "MC Truth",
      'xtitle': "Primary TPC Track True dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [400,0,50],
      'var': "primTrkTruedEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primMCdEdxs",
      "title": "MC Trajectory",
      'xtitle': "Primary TPC Track True dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [400,0,50],
      'var': "primMCdEdxs",
      'cuts': weightStr+"*(primMCXs>2. && primMCXs < 47. && primMCYs > -23. && primMCYs < 23. && primMCZs > 0. && primMCZs < 90 && primMClastXs>2. && primMClastXs < 47. && primMClastYs > -23. && primMClastYs < 23. && primMClastZs > 0. && primMClastZs < 90 )",
      #'normalize': True,
      'logy': logy,
    },
  ]
  for i in range(len(histConfigs)):
    histConfigs[i]["color"] = COLORLIST[i]
#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="CosmicsTrue_dEdx")

  histConfigs = [
    {
      'name': "primTrkdEdxs_zoom",
      "title": "Reco",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,10],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkTruedEdxs_zoom",
      "title": "MC Truth",
      'xtitle': "Primary TPC Track True dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,10],
      'var': "primTrkTruedEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primMCdEdxs_zoom",
      "title": "MC Trajectory",
      'xtitle': "Primary TPC Track True dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,10],
      'var': "primMCdEdxs",
      'cuts': weightStr+"*(primMCXs>2. && primMCXs < 47. && primMCYs > -23. && primMCYs < 23. && primMCZs > 0. && primMCZs < 90 && primMClastXs>2. && primMClastXs < 47. && primMClastYs > -23. && primMClastYs < 23. && primMClastZs > 0. && primMClastZs < 90 )",
      #'normalize': True,
      'logy': logy,
    },
  ]
  for i in range(len(histConfigs)):
    histConfigs[i]["color"] = COLORLIST[i]
#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="UnifIso_dEdxZoom")

  histConfigs = [
    {
      'name': "primTrkdQdxs_zoom",
      'title': "Reco [10.8*ADC/cm]",
      'xtitle': "Primary TPC Track dQ/dx",# [10*ADC/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,1e5],
      'var': "10.8*primTrkdQdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkTruedQdxs_zoom",
      'title': "MC Truth [e^{-}/cm]",
      'xtitle': "Primary TPC Track True dQ/dx",# [e^{-}/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,1e5],
      'var': "primTrkTruedQdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
  ]
  for i in range(len(histConfigs)):
    histConfigs[i]["color"] = COLORLIST[i]
#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="CosmicsTrue_dQdxZoom")


  histConfigs = [
    {
      "title": "All",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Normalized Events",
      'binning': [200,0,4],
      'var': "primTrkdEdxs",
      'cuts': "1",
      'normalize': True,
      'logy': False,
    },
    {
      "title": "Res Ranges Correct",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Normalized Events",
      'binning': [200,0,4],
      'var': "primTrkdEdxs",
      'cuts': "(primTrkResRanges[0] > 1.)",
      'normalize': True,
      'logy': False,
    },
    {
      "title": "Res Ranges Correct & 1st 50 hits",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Normalized Events",
      'binning': [200,0,4],
      'var': "primTrkdEdxs",
      'cuts': "(primTrkResRanges[0] > 1.)*(Iteration$ < 50)",
      'normalize': True,
      'logy': False,
    },
    {
      "title": "Res Ranges Correct & 1st 10 hits",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Normalized Events",
      'binning': [200,0,4],
      'var': "primTrkdEdxs",
      'cuts': "(primTrkResRanges[0] > 1.)*(Iteration$ < 10)",
      'normalize': True,
      'logy': False,
    },
    {
      "title": "Res Ranges Correct & 1st 5 hits",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Normalized Events",
      'binning': [200,0,4],
      'var': "primTrkdEdxs",
      'cuts': "(primTrkResRanges[0] > 1.)*(Iteration$ < 5)",
      'normalize': True,
      'logy': False,
    },
  ]
  for i in range(len(histConfigs)):
    histConfigs[i]["color"] = COLORLIST[i]
#  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="UnifIso_dEdxZoomHits")

  histConfigs = [
    {
      'title': "True No-Cuts",
      'xtitle': "|cos(#theta_{pitch})|",
      'ytitle': "Normalized events / bin",
      'binning': [30,0,1],
      'var': "fabs(cos(trueStartTheta)*cos(-pi/3.)+sin(trueStartTheta)*sin(-pi/3.)*cos(trueStartPhi-0.5*pi))",
      'cuts': "",
      #'normalize': True,
      'logy': False,
    },
    {
      'title': "True w/ Reco Track",
      'xtitle': "|cos(#theta_{pitch})|",
      'ytitle': "Normalized events / bin",
      'binning': [30,0,1],
      'var': "fabs(cos(trueStartTheta)*cos(-pi/3.)+sin(trueStartTheta)*sin(-pi/3.)*cos(trueStartPhi-0.5*pi))",
      'cuts': "(iBestMatch >= 0)",
      #'normalize': True,
      'logy': False,
    },
    {
      'title': "Reconstructed 1st Hit",
      'xtitle': "|cos(#theta_{pitch})|",
      'ytitle': "Normalized events / bin",
      'binning': [30,0,1],
      'var': "0.4/primTrkPitches",
      'cuts': "(Iteration$ == 0)",
      #'normalize': True,
      'logy': False,
    },
  ]
  for i in range(len(histConfigs)):
    histConfigs[i]["color"] = COLORLIST[i]
  plotManyHistsOnePlot(fileConfigs,histConfigs,c,"cosmicanalyzer/tree",nMax=NMAX,outPrefix="UnifIso_CosThetaPitch")
