//
// RooFit model of LArIAT Time of Flight System
//


#include "RooRealVar.h"
#include "RooDataSet.h"
#include "RooGaussian.h"
#include "RooFormulaVar.h"
#include "RooGenericPdf.h"
#include "RooPlot.h"
#include "TCanvas.h"
#include "TAxis.h"
#include "TH1.h"
using namespace RooFit;

void tofRooFit()
{
   // S e t u p   c o m p o n e n t   p d f s 
   // ---------------------------------------

   // Construct observable
   RooRealVar mass2("mass2","Mass Squared [MeV^{2}]",-5e4,3e6);

   // Construct nuisance parameters
   RooRealVar p0("p0","Momentum pre-smear [MeV]",500);
   //RooRealVar dt0("dt0","#Delta t pre-smear [ns]",22);
   RooRealVar d("d","Distance [m]",6);
   RooRealVar sigmadt("sigmadt","#Delta t Smearing Sigma [ns]",0.5);
   RooRealVar f("f","f, the Momentum Coefficient",1.,0.5,2.);
   RooRealVar sigmap("sigmap","Momentum Smearing Sigma [MeV]",50.);
   RooRealVar true_mass("true_mass","True Mass [MeV]",105.);

   // Construct dependent parameters

   RooRealVar p("p","Momentum [MeV]",0.,2000.);
   RooRealVar dt("dt","#Delta t [ns]",0.,100.);
   RooFormulaVar dt0("dt0","#Delta t pre-smear [ns]",
                        "sqrt(@2*@2/0.29979/0.29979*(1+@1*@1/@0/@0))",
                        RooArgList(p0,true_mass,d));

   RooFormulaVar mass2_param("mass2_param","Mass Squared generated by model [MeV]",
                        "@0*@0*(@1*@1*0.29979*0.29979/@2/@2-1.)",
                        RooArgList(p,dt,d));

   RooFormulaVar mass_param("mass_param","Mass generated by model [MeV]",
                        "sqrt(mass2_param)",
                        RooArgList(mass2_param));

   // Construct Smearing PDFs
   RooGaussian gauss_dt("gauss_dt","#Delta t Smearing Gaussian",dt,dt0,sigmadt);
   RooGaussian gauss_p("gauss_p","Momentum Smearing Gaussian",p,p0,sigmap);

   // Construct final mass2 PDF out of its dependent parameters
   //RooRealVar dummy("dummy","dummy",0.1);
   //RooGaussian mass2_model("mass2_model","Mass Squared Model", mass2,mass2_param,dummy);
   RooProdPdf smearing_model("smearing_model","Gaussian Smearing Model",RooArgList(gauss_dt,gauss_p));

   // S a m p l e ,   f i t   a n d   p l o t   c o n v o l u t e d   p d f 
   // ----------------------------------------------------------------------

   // Sample 1000 events in x from gxlx
   //RooDataSet* toy_data = gauss_dt.generate(RooArgList(dt),100);
   RooDataSet* toy_data = smearing_model.generate(RooArgList(p,dt),100);

//   // Fit gxlx to data
//   //mass2_model.fitTo(*data);
//
//   // Plot data, landau pdf, landau (X) gauss pdf
   RooPlot* frame = mass_param.frame(Title("Muon Mass"));
   toy_data->plotOn(frame);
//   mass2_model.plotOn(frame);
//
//   // Draw frame on canvas
//   TCanvas* c = new TCanvas("c");
//   //gPad->SetLeftMargin(0.15); frame->GetYaxis()->SetTitleOffset(1.4);
//   frame->Draw();

}



